### ISSUE TITLE
bloom-release track and rosdistro arguments are redundant

### ISSUE THREAD

**Issue by ahendrix** [ros-infrastructure/bloom#181]
The `--track` and `--rosdistro` arguments to bloom-release are largely redundant. I propose two possible solutions:
- If `--rosdistro` is specified and `--track` is not, assume they are the same
  OR
- If `--rosdistro` is specified and `--track` is not, go to the appropriate distro file, find the release repository, pull down the track config from the release repository, and find the track that matches the specified rosdistro. Prompt the user if there is more than one track that matches.

**Comment by DLu** [comment]
Closed by #459

**Comment by trainman419** [comment]
Awesome! Thank you @DLu !
