### ISSUE TITLE
support upstream git repositories with submodules

### ISSUE THREAD

**Issue by wjwwood** [ros-infrastructure/bloom#217]
See: https://github.com/ros-infrastructure/bloom/issues/202

This will require a patch in `vcstools`.

**Comment by asmodehn** [comment]
I am using bloom-release 0.5.20 and I still experience this problem.
I d like to solve it asap since I use a few repositories with submodules ( to be able to embed extra uptodate python-only packages into a ros package. )
Please , let me know the best way I can help, thanks.

**Comment by tfoote** [comment]
There's a workaround mentioned in #202 and you could probably locally make the changes in vcstools/vcstools#88 or vcstools/vcstools#95 

To help solve this properly you could work on solving the outstanding problems in those tickets so it can be released into `vcstools` which `bloom` builds upon.

**Comment by asmodehn** [comment]
See https://github.com/vcstools/vcstools/pull/108 for a fix for https://github.com/vcstools/vcstools/pull/95
Thanks for letting me know if anything else is needed, there or somewhere else.
I might have a tiny bit of time to spend on this, since it is critical for me right now.

**Comment by asmodehn** [comment]
So if anyone needs this feature urgently, I recently tested with : 
- trusty
- indigo
- bloom 0.5.20
- vcstools https://github.com/vcstools/vcstools/commit/dbe026c2c956d3fde808185e525a027a3b658828 from https://github.com/vcstools/vcstools/pull/108
- git > v1.8.3
- buildbot-ros with this change https://github.com/yujinrobot/buildbot-ros/commit/d3ccbd8b2059d747c2c30197e79aebfdfd093ade

And I could release a package from a repository containing a submodule : https://github.com/asmodehn/celeros/tree/indigo-devel/deps 
The (private) release repo contains the submodule,and I was able to build on buildbot-ros.
It's currently sitting in a private release repository, but I ll release it on public rosdistro when all the submodules issues are solved.

**Comment by k-okada** [comment]
are we ready for this? if so, we can solve https://github.com/jsk-ros-pkg/jsk_recognition/issues/1817 issue

**Comment by wjwwood** [comment]
Have you tried releasing a package with this pr of bloom? It would be good to see that it works before merging it with master and releasing it for everyone that uses bloom.

**Comment by wjwwood** [comment]
Ah, this isn't a pr. @asmodehn are you saying that bloom works as-is? The upstream vcstools pr's (or their replacements) have been merged and I think released as well.

**Comment by k-okada** [comment]
I think we have to release new version of vcstools, that includes
https://github.com/vcstools/vcstools/pull/110

--
◉ Kei Okada

**Comment by asmodehn** [comment]
That was a while ago but from what I can remember, bloom worked as is, once vcstool had the submodule support added.

I had to patch buildbot-ros to be able to use submodules ( and maybe other things ? ) there, but I havent used that for a very very long time...

Since that I dropped the idea of doing releases for this package with submodule via private buildbot because of lack of time to maintain all this, and I now plan to release this package using the ros buildfarm ( it took and will still take quite a bit of work because I need to depend on many pip packages - but thats another story )

So vcstool release should be enough to get the ball rolling for other submodule usecases. Maybe the buildfarm will need some adjustments ?

**Comment by wjwwood** [comment]
`vcstools` version `0.1.39` was released a couple of days ago.

**Comment by peterbarker** [comment]
Apparently builds are now broken; pursuing this to its end might be worthwhile!

https://github.com/mavlink/mavlink/pull/618

**Comment by wjwwood** [comment]
I think it just needs to be attempted now that vcstools has been released. From the linked issue it isn't clear to me what the remaining issues are.
