### ISSUE TITLE
bloom relies on an English git version

### ISSUE THREAD

**Issue by vrabaud** [ros-infrastructure/bloom#300]
Just to say, my git was in French to see the translation of some words :)
Still, those text parsing checks seem hard to handle and not future proof. In my case, it happened here:
https://github.com/ros-infrastructure/bloom/blob/master/bloom/git.py#L408
Definitely not a priority. Thx !
And the error was:

    ++ git status:

    Sur la branche master
    Votre branche est à jour avec 'origin/master'.

    rien à valider, la copie de travail est propre
    Current git working branch has local changes

**Comment by ahornung** [comment]
Since I ran into this again and the error is not really apparent from the messages, could we have a simple check and warning added into bloom?

**Comment by wjwwood** [comment]
Yes, next time I spend time on bloom I'll at least add a check.

**Comment by vrabaud** [comment]
btw, I had a similat problem and I switched to a Popen with a custom env:
https://github.com/wg-perception/reconstruction/commit/e544f42549a2dc508873c1e1e8ca9f837cb9a025
(set LC_ALL in env, stdout in Popen and you will be good to go no ?)

**Comment by wjwwood** [comment]
That should work, I have another patch primed in master, I'll try to sneak this one in to and release later today if it works out.

**Comment by wjwwood** [comment]
Can you guys try https://github.com/ros-infrastructure/bloom/pull/365?

**Comment by ahornung** [comment]
Works with bloom 0.5.20, thanks! :+1:

**Comment by davetcoleman** [comment]
I'm getting this same error now except I've always used US English. It might be because I just upgraded to git 2.9.2 per @wjwwood  and the output is slightly different:

```
Releasing 'rviz_visual_tools' using release track 'indigo'
==> git-bloom-release indigo

++ git status:

On branch master
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)
nothing to commit, working tree clean
Current git working branch has local changes
Release failed, exiting.
```

**Comment by wjwwood** [comment]
I cannot reproduce this with `2.9.2`. Maybe there is some other circumstance which is causing your problem?

**Comment by davetcoleman** [comment]
Thanks for attempting to reproduce, I've moved the issue https://github.com/ros-infrastructure/bloom/issues/398
