### ISSUE TITLE
Default release build flags for packages

### ISSUE THREAD

**Issue by wjwwood** [ros-infrastructure/bloom#327]
This currently applies to Ubuntu/Debian but could also affect others by way of common policy. Currently we do not explicitly set any release related compiler or CMake flags like `-DNDEBUG`, `-O3`, or `-DCMAKE_BUILD_TYPE=Release`, the question is should we and if so which ones?

tl;dr:

As I see it we can choose one of these options:
- Add `-DCMAKE_BUILD_TYPE=Release` (effectively `-O3 -DNDEBUG`) to the bloom template
  - This will (through attrition) make it so all packages have these flags
  - They must explicitly opt-out to return to the current settings
- Same as above but only `-NDEBUG`
- Again the same but only `-O3`
- Or do nothing in bloom, but write up how to explicitly opt-into these flags
  - This allows developers who care to opt-in to potentially breaking compiler flags

I am leaning towards the third option, but I would like some feedback @dirk-thomas @tfoote @mikeferguson @isucan @davetcoleman @mintar @tlind @j-rivero

---

Related tickets:
- https://github.com/ros-visualization/rviz/issues/775
- https://github.com/ros-planning/moveit_core/pull/204
- https://github.com/ros-infrastructure/bloom/pull/278

---

Currently we pass some non-release related flags through `deb_helper`:

https://github.com/ros-infrastructure/bloom/blob/master/bloom/generators/debian/templates/rules.em#L27-30

The `CATKIN_BUILD_BINARY_PACKAGE` CMake argument is how we disable installing of `setup.bash`.

My understanding (given the research I have done into things) is that `deb_helper` inserts default values into the build, for both CMake and the compiler and some of those defaults come from `dpkg-buildflags`. This happens automatically as of debhelper version 9 (which bloom is already using, see: https://github.com/ros-infrastructure/bloom/pull/278), see: https://wiki.debian.org/HardeningWalkthrough#Enabling_dpkg-buildflags_in_your_debian.2Frules_files

In accordance with this, `deb_helper` prepends our CMake variables with `-DCMAKE_BUILD_TYPE=None`. This (I think) prevents CMake from overriding by default the flags `deb_helper` passes to the compiler. We could override this by adding `-DCMAKE_BUILD_TYPE=Release` in the bloom rules template linked above, however, I think this potentially dangerous.

From my experience the `-DCMAKE_BUILD_TYPE=Release` essentially boils down to `-O3` and `-DNDEBUG` on our Ubuntu buildfarm, see: https://github.com/ros-visualization/rviz/issues/775#issuecomment-59185412

I would consider `-O3` too aggressive, because it can actually affect the behavior of code, not just the performance, so changing from opt-in to opt-out on that one will potentially break packages for people who have not explicitly checked this. But then again, this is more likely to have more utility than for the many packages it could speed up than the few packages it might break. Either way it is hard to estimate if it is a net win or loss to add `-O3` for all packages automatically.

On the other hand, `-DNDEBUG` should not exclude code which affects the behavior of a system, but still could potentially be bad if the developer of a package did something odd like defining a variable inside the debug area and using it outside. Given that caveat I would feel better about adding `-DNDEBUG` automatically to all packages (requiring them to opt-out explicitly if desired) than doing the same for `-O3`.

**Comment by tfoote** [comment]
So, I'm not sure we want to reopen this discussion at the moment but debian policy calls for `-O2` and `-g` by default with `-O3` available to use by packages managers. [Debian Policy 10.1](https://www.debian.org/doc/debian-policy/ch-files.html)

**Comment by mintar** [comment]
@tfoote : So, what changes to the current state are you suggesting? Adding `-g` and/or removing `-DNDEBUG`? The debian policy says nothing about `NDEBUG`.

**Comment by tfoote** [comment]
Upon review I think that we're compliant so we don't need to do anything. Adding RelWithDebInfo was proposed briefly in #374 and the link to the debian policy came up, which was not previously linked in this thread so I wanted to add it for reference. But we look to already have `-g` `-O2` and we should keep the `-DNDBUG` so we're compliant as is.
