### ISSUE TITLE
bloom-release --version gives git checkout errors

### ISSUE THREAD

**Issue by trainman419** [ros-infrastructure/bloom#339]
There's something very strange here:

```
$ bloom-release --version
'execute_command' failed to call 'git checkout "master"' which had a return code (1):
```
error: pathspec 'master' did not match any file(s) known to git.

```
Failed to checkout to 'master' because the working directory CalledProcessError: Command 'git checkout "master"' returned non-zero exit status 1

++ git status:

# On branch hydro-devel
nothing to commit (working directory clean)
'execute_command' failed to call 'git checkout "master"' which had a return code (1):
```
error: pathspec 'master' did not match any file(s) known to git.

```
Failed to checkout to 'master' because the working directory CalledProcessError: Command 'git checkout "master"' returned non-zero exit status 1

++ git status:

# On branch hydro-devel
nothing to commit (working directory clean)
0.5.15
```

It doesn't do this if I'm in a directory that isn't a git repository, or if I'm in a git repository which has a valid master branch.

I'm guessing that this part of the version check and isn't related to the release functionality, so I'm going to try doing my releases and post here if they fail.

**Comment by wjwwood** [comment]
I'm not sure I can fix this easily. None of bloom is designed to handle multiple remotes properly.

I have modified the behavior to give a more meaningful error:

```
% bloom-release -r indigo -t indigo serial
Current git repository has multiple remotes. If you are running bloom-release, please change directories.
```

I'll open a pull request soon.
