### ISSUE TITLE
bloom-release should show all missing rosdep keys at once

### ISSUE THREAD

**Issue by dirk-thomas** [ros-infrastructure/bloom#341]
Currently when calling `bloom-release` it prints the first rosdep key missing. After continuing it might print the next one and so on. It would be much more convenient if it would show *all* missing rosdep keys in the first place.

This is especially inconvenient when releasing a new ROS distro.

**Comment by wjwwood** [comment]
I've updated the script considerably, fixing several bugs and improving the readability.

**Comment by wjwwood** [comment]
I opened a pull request: https://github.com/ros-infrastructure/bloom/pull/349
