### ISSUE TITLE
Creating a fork of rosdistro needs to wait... and retrieve actual fork repo name

### ISSUE THREAD

**Issue by asmodehn** [ros-infrastructure/bloom#375]
I am using bloom 0.5.20.

I am also using a different rosdistro to be able to release private packages. This rosdistro is available on github ( so that we can use the usual bloom process for it as well ), since there is no sensitive information in the rosdistro itself.

When trying to release a package ( and after modifying ROSDISTRO_INDEX_URL to point to the one containing private packages, and importing ROS rosdep using https://github.com/mikepurvis/rosdep-generator ), this happens : 
```
alexv@asmodehn:~/ROS/gopher_rocon/src/gopher_msgs$ bloom-release --rosdistro indigo --track indigo gopher_msgs --pull-request-only
ROS Distro index file associate with commit 'd120e616cb6eb9eb7d3152f31c5edf5c58be4e54'
New ROS Distro index url: 'https://raw.githubusercontent.com/yujinrobot/rosdistro/d120e616cb6eb9eb7d3152f31c5edf5c58be4e54/index.yaml'
Specified repository 'gopher_msgs' is not in the distribution file located at 'https://raw.githubusercontent.com/yujinrobot/rosdistro/d120e616cb6eb9eb7d3152f31c5edf5c58be4e54/indigo/distribution.yaml'
Did you mean one of these: 'gopher_msgs'?
Could not determine release repository url for repository 'gopher_msgs' of distro 'indigo'
You can continue the release process by manually specifying the location of the RELEASE repository.
To be clear this is the url of the RELEASE repository not the upstream repository.
For release repositories on GitHub, you should provide the `https://` url which should end in `.git`.
Here is the url for a typical release repository on GitHub: https://github.com/ros-gbp/rviz-release.git
==> Looking for a release of this repository in a different distribution...
No reasonable default release repository url could be determined from previous releases.
Release repository url [press enter to abort]: https://bitbucket.org/yujinrobot/gopher_msgs-release.git
==> Fetching 'gopher_msgs' repository from 'https://bitbucket.org/yujinrobot/gopher_msgs-release.git'
Cloning into '/tmp/tmpFGGD2f'...
remote: Counting objects: 286, done.
remote: Compressing objects: 100% (196/196), done.
remote: Total 286 (delta 53), reused 283 (delta 53)
Receiving objects: 100% (286/286), 37.42 KiB | 0 bytes/s, done.
Resolving deltas: 100% (53/53), done.
Checking connectivity... done.
==> Generating pull request to distro file located at 'https://raw.githubusercontent.com/yujinrobot/rosdistro/d120e616cb6eb9eb7d3152f31c5edf5c58be4e54/indigo/distribution.yaml'
Unified diff for the ROS distro file located at '/tmp/tmpd6x50Y/gopher_msgs-0.2.0-0.patch':
--- d120e616cb6eb9eb7d3152f31c5edf5c58be4e54/indigo/distribution.yaml
+++ d120e616cb6eb9eb7d3152f31c5edf5c58be4e54/indigo/distribution.yaml
@@ -129,11 +129,20 @@
       type: git
       url: https://bitbucket.org/yujinrobot/gopher_msgs.git
       version: indigo
+    release:
+      packages:
+      - gopher_msgs
+      - gopher_navi_msgs
+      - gopher_semantic_msgs
+      - gopher_std_msgs
+      tags:
+        release: release/indigo/{package}/{version}
+      url: https://bitbucket.org/yujinrobot/gopher_msgs-release.git
+      version: 0.2.0-0
     source:
       type: git
       url: https://bitbucket.org/yujinrobot/gopher_msgs.git
       version: indigo
     status: developed
-
 type: distribution
 version: 1
==> Checking on GitHub for a fork to make the pull request from...
==> asmodehn/rosdistro is not a fork, searching...
Could not find a fork of yujinrobot/rosdistro on the asmodehn GitHub account.
Would you like to create one now?
Continue [Y/n]? 
==> Using this fork to make a pull request from: asmodehn/rosdistro
==> Cloning asmodehn/rosdistro...
==> mkdir -p rosdistro
==> git init
Initialized empty Git repository in /tmp/PE5Q4H/rosdistro/.git/
Failed to open pull request: GithubException - Failed to list branches for 'asmodehn/rosdistro' using url '/repos/asmodehn/rosdistro/branches?page=1&per_page=2': 404 Not Found
```

So it seems that the rosdistro fork has not been created yet.
However a few minutes later it was accessible, and I could release properly => the bloom-release script needs to wait for that repository to be available.

While messing around with this, I had also a fork of the ROS rosdistro/rosdistro in my repositories.
So another repository with the same name was already there ( but not a fork of the rosdistro we use ) and the repository created by bloom-release call was actually different than the one requested ( ex : rosdistro-1 )
=> the bloom-release script needs to retrieve the name of the actual rosdistro fork after creation.

After figuring this out, I removed all my "rosdistro" repositories, and waited for the created fork to be available and bloom-release worked fine.
I don't have time to investigate these in details now, so no PR for this yet.

**Comment by wjwwood** [comment]
I could see how this might be an issue, but I don't have time to dig into it and come up with a solution. I'll gladly look at a pull request though.

**Comment by asmodehn** [comment]
I finally got around to investigate these issues : 

* [ ] 1) while searching through the repositories of the user, no fork of rosdistro can be found because "parent" field has been removed by github from the API at some point.
* [ ] 2) when forking a rosdistro repository the actual repository name was not retrieved
* [ ] 3) when forking a rosdistro repository, it takes time and the script does not wait for it to be available

I think I have a beginning of fix for 1) and 2) in  https://github.com/ros-infrastructure/bloom/pull/376.
Please have a look and let me know what you think...
