### ISSUE TITLE
Expanding 'debian/control.em' -> 'debian/control' would create two whiteblank lines

### ISSUE THREAD

**Issue by kintzhao** [ros-infrastructure/bloom#391]
when i run bloom-release to creator a new package version.  
==> In place processing templates in 'debian' folder.
Expanding 'debian/gbp.conf.em' -> 'debian/gbp.conf'
Expanding 'debian/compat.em' -> 'debian/compat'
Expanding 'debian/control.em' -> 'debian/control'
Expanding 'debian/rules.em' -> 'debian/rules'
Expanding 'debian/changelog.em' -> 'debian/changelog'
Creating tag: debian/ros-indigo-rplidar-ros_1.5.2-1_saucy

but the 'debian/control'  would expand two extra whitespace lines. like this 

> Source: ros-indigo-rplidar-ros
> Section: misc
> Priority: extra
> Maintainer: Slamtec ROS Maintainer <ros@slamtec.com>
> Build-Depends: debhelper (>= 9.0.0), ros-indigo-catkin, ros-indigo-rosconsole, ros-indigo-roscpp, ros-indigo-sensor-msgs, ros-indigo-std-srvs
> Homepage: 
> Standards-Version: 3.9.2
> 
> Package: ros-indigo-rplidar-ros
> Architecture: any
> Depends: ${shlibs:Depends}, ${misc:Depends}, ros-indigo-rosconsole, ros-indigo-roscpp, ros-indigo-sensor-msgs, ros-indigo-std-srvs
> 
> 
> Description: The rplidar ros package support rplidar and rplidar A2

expanded by the control.em file 

> Source: @(Package)
> Section: misc
> Priority: extra
> Maintainer: @(Maintainer)
> Build-Depends: debhelper (>= @(debhelper_version).0.0), @(', '.join(BuildDepends))
> Homepage: @(Homepage)
> Standards-Version: 3.9.2
> 
> Package: @(Package)
> Architecture: any
> Depends: ${shlibs:Depends}, ${misc:Depends}, @(', '.join(Depends))
> @[if Conflicts]Conflicts: @(', '.join(Conflicts))@\n@[end if]@
> @[if Replaces]Replaces: @(', '.join(Replaces))@\n@[end if]@
> Description: @(Description)

but this file can be created  by  another pc  whitout  two extra whitespace lines . 
 How can i check it ?  what is the reason for the result.

--------------------------------------------
yhzhao@yhzhao:~$ pip freeze
BeautifulSoup==3.2.1
Jinja2==2.7.2
MarkupSafe==0.18
PAM==0.4.2
Pillow==2.3.0
PyOpenGL==3.0.2
PyYAML==3.10
Pygments==1.6
SecretStorage==2.0.0
Sphinx==1.2.2
Twisted-Core==13.2.0
Twisted-Web==13.2.0
VTK==5.8.0
actionlib==1.11.3
adium-theme-ubuntu==0.3.4
apt-xapian-index==0.45
argparse==1.2.1
base-local-planner==1.12.7
beautifulsoup4==4.2.1
bloom==0.5.21
bondpy==1.7.16
boto==2.20.1
bzr==2.7.0dev1
camera-calibration==1.12.15
camera-calibration-parsers==1.11.10
capabilities==0.2.0
catkin==0.6.16
catkin-pkg==0.2.10
catkin-tools==0.4.2
chardet==2.0.1
colorama==0.2.5
command-not-found==0.3
configobj==4.7.2
create-dashboard==2.3.1
create-driver==2.3.0
create-node==2.3.0
cv-bridge==1.11.11
debtagshw==0.1
defer==1.0.6
diagnostic-analysis==1.8.8
diagnostic-common-diagnostics==1.8.8
diagnostic-updater==1.8.8
dirspec==13.10
docutils==0.11
duplicity==0.6.23
dynamic-reconfigure==1.5.38
empy==3.3.2
epydoc==3.0.1
futures==2.1.6
gazebo-plugins==2.4.9
gazebo-ros==2.4.9
gencpp==0.5.3
genlisp==0.4.15
genmsg==0.5.6
genpy==0.5.7
html5lib==0.999
httplib2==0.8
image-geometry==1.11.11
interactive-markers==1.11.1
keyring==3.5
kitchen==1.1.1
kobuki-dashboard==0.4.2
kobuki-testsuite==0.6.6
laser-geometry==1.6.4
launchpadlib==1.10.2
lazr.restfulclient==0.13.3
lazr.uri==1.0.3
lockfile==0.8
lxml==3.3.3
matplotlib==1.3.1
mercurial==2.8.2
message-filters==1.11.16
netifaces==0.8
nose==1.3.1
numpy==1.8.2
oauth==1.0.1
oauthlib==0.6.1
oneconf==0.3.7.14.04.1
openshot==1.4.3
osrf-pycommon==0.1.2
pano-ros==2.3.3
paramiko==1.10.1
pexpect==3.1
piston-mini-client==0.7.5
pluginlib==1.10.1
psutil==1.2.1
pyOpenSSL==0.13
pycrypto==2.6.1
pycups==1.9.66
pydot==1.0.28
pygobject==3.12.0
pygpgme==0.3
pymongo==2.6.3
pyparsing==2.0.1
pyserial==2.6
pysmbc==1.0.14.1
python-apt==0.9.3.5ubuntu2
python-cloudfiles==1.7.10
python-dateutil==1.5
python-debian==0.1.21-nmu2ubuntu2
python-distutils-extra==2.38
python-qt-binding==0.2.17
pytz==2012c
pyxdg==0.25
qt-dotgraph==0.2.29
qt-gui==0.2.29
qt-gui-cpp==0.2.29
qt-gui-py-common==0.2.29
quickly-lens-templates==0.0.3
reportlab==3.0
requests==2.2.1
resource-retriever==1.11.6
rocon-app-manager==0.7.13
rocon-app-utilities==0.7.13
rocon-apps==0.7.13
rocon-console==0.1.23
rocon-ebnf==0.1.23
rocon-gateway==0.7.10
rocon-gateway-utils==0.7.10
rocon-hub==0.7.10
rocon-hub-client==0.7.10
rocon-interactions==0.1.23
rocon-launch==0.1.23
rocon-master-info==0.1.23
rocon-python-comms==0.1.23
rocon-python-redis==0.1.23
rocon-python-utils==0.1.23
rocon-python-wifi==0.1.23
rocon-qt-library==0.7.12
rocon-remocon==0.7.12
rocon-semantic-version==0.1.23
rocon-uri==0.1.23
roman==2.0.0
rosbag==1.11.16
rosboost-cfg==1.11.11
rosclean==1.11.11
roscreate==1.11.11
rosdep==0.11.4
rosdistro==0.4.7
rosdoc-lite==0.2.5
rosgraph==1.11.16
rosinstall==0.7.7
roslaunch==1.11.16
roslib==1.11.11
roslint==0.10.0
roslz4==1.11.16
rosmake==1.11.11
rosmaster==1.11.16
rosmsg==1.11.16
rosnode==1.11.16
rosparam==1.11.16
rospkg==1.0.39
rospy==1.11.16
rospy-message-converter==0.4.0
rosservice==1.11.16
rostest==1.11.16
rostopic==1.11.16
rosunit==1.11.11
roswtf==1.11.16
rqt-action==0.3.12
rqt-bag==0.3.12
rqt-bag-plugins==0.3.12
rqt-console==0.3.12
rqt-dep==0.3.12
rqt-graph==0.3.12
rqt-gui==0.2.14
rqt-gui-py==0.2.14
rqt-image-view==0.3.12
rqt-launch==0.3.12
rqt-logger-level==0.3.12
rqt-moveit==0.4.2
rqt-msg==0.3.12
rqt-nav-view==0.4.2
rqt-plot==0.3.12
rqt-pose-view==0.4.2
rqt-publisher==0.3.12
rqt-py-common==0.3.12
rqt-py-console==0.3.12
rqt-reconfigure==0.3.12
rqt-robot-dashboard==0.4.2
rqt-robot-monitor==0.4.2
rqt-robot-steering==0.4.2
rqt-runtime-monitor==0.4.2
rqt-rviz==0.4.2
rqt-service-caller==0.3.12
rqt-shell==0.3.12
rqt-srv==0.3.12
rqt-tf-tree==0.4.2
rqt-top==0.3.12
rqt-topic==0.3.12
rqt-web==0.3.12
rviz==1.11.10
sensor-msgs==1.11.8
sessioninstaller==0.0.0
simplejson==3.3.1
six==1.5.2
smach==2.0.0
smach-ros==2.0.0
smclib==1.7.16
software-center-aptd-plugins==0.0.0
sound-play==0.2.10
ssh-import-id==3.21
system-service==0.1.6
tf==1.11.7
tf-conversions==1.11.7
tf2-geometry-msgs==0.5.12
tf2-kdl==0.5.12
tf2-py==0.5.12
tf2-ros==0.5.12
tf2-sensor-msgs==0.5.12
trollius==1.0.1
unique-id==1.0.5
unity-lens-photos==1.0
unity-scope-sshsearch==0.1
unity-singlet==0.2.2
urllib3==1.7.1
vboxapi==1.0
vcstools==0.1.38
wadllib==1.3.2
warehouse-ros==0.8.8
wheel==0.24.0
winpdb==1.4.8
world-canvas-client-py==0.1.0
world-canvas-server==0.1.0
world-canvas-utils==0.1.0
wsgiref==0.1.2
wstool==0.1.12
wxPython==2.8.12.1
wxPython-common==2.8.12.1
xacro==1.9.5
xdiagnose==3.6.3build2
youtube-dl==2014.02.17
zope.interface==4.0.5

**Comment by kintzhao** [comment]
yhzhao@yhzhao:~$ pip freeze |grep rosdis
rosdistro==0.4.7

but it is the latest version? what is your new version, how to get it?
http://download.ros.org/downloads/rosdistro/



you mean is that i should update the repo https://github.com/kintzhao/rosdistro to new ?
keep REP to 0143 ?

-# see REP 143: http://ros.org/reps/rep-0143.html
+# see REP 141: http://ros.org/reps/rep-0141.html

what is your mean of

you have an out of date version of python-rosdistro
which is the latest ?

**Comment by tfoote** [comment]
No, there is the rosdistro index ros/rosdistro and the library python-rosdistro from ros-infrastructure/rosdistro. 

0.4.7 is the latest, however if you get the 141 output instead of the 143 output it suggests that you do not have [this](https://github.com/ros-infrastructure/rosdistro/commit/a94e9fe43f03828a9af88200807df259b7f2e1ed) fix in your working copy.(from [62](https://github.com/ros-infrastructure/rosdistro/pull/62)) It can be seen in the history as merged in 0.4.4 https://github.com/ros-infrastructure/rosdistro/commits/master  

This suggests that where you're running `pip freeze` and where you're running `bloom-release` are different environments somehow? We've tested with the same inputs and gotten the correct results. As far as I can tell there's something broken in your environment. I'd really suggest that you start with a clean VM or docker instance, keep the full command line history and if you can reproduce your problem we can try to help you more.

**Comment by kintzhao** [comment]
I am running bloom-release at VM  (i have update rosdistro from 1.4.2 to 1.4.7)  . But how can i repair  and check my environment  at PC instead of VM . 

the upstrem :    https://github.com/robopeak/rplidar_ros.git
 release :         https://github.com/kintzhao/rplidar_ros-release.git 
rosdistro :          https://github.com/kintzhao/rosdistro/tree/bloom-rplidar_ros-0

**Comment by kintzhao** [comment]
new PR is 11487.

**Comment by kintzhao** [comment]
thanks, the new version is passing which was released at VM ,   but i want to check why my pc create two white blank line and how to check my environment .   which python app can distrub the result of bloom-release ?  How to repair it and check it.  can you give me some advice?

**Comment by tfoote** [comment]
My recommendation would be to start uninstalling and reinstalling as much as possible. Depending on how long things have gone and what sort of things have happened to your system you may find it's easier to reinstall. The errors seem pretty pernicious which will make it hard to debug/diagnose.
