### ISSUE TITLE
Error when releasing: "Current git working branch has local changes"

### ISSUE THREAD

**Issue by mwerlberger** [ros-infrastructure/bloom#395]
When releasing (a private) github repo (initial release), I get the following error in the end:
```
==> git-bloom-release jade

++ git status:

On branch master
Your branch is ahead of 'origin/master' by 3 commits.
  (use "git push" to publish your local commits)
nothing to commit, working tree clean
Current git working branch has local changes
Release failed, exiting.
```

Strangely, I did releases from this machine so I don't think that it is a setup issue. Furthermore, the branch should not be 'dirty' as the release process does a clean checkout anyways?

Thanks for any hints or suggestions on how to fix this issue.
(btw. system uses LANGUAGE=en and LANG=en_US.UTF-8 so its not the non-english git issue...)

The error occurs after setting the release repository push url. The release repo is newly created.

**Comment by wjwwood** [comment]
@mwerlberger I can't tell from this info what the issue might be. Could you share the complete bloom log with me, either publicly in a gist.github.com or privately via email? The complete log is stored in `~/.bloom_logs`.

**Comment by mwerlberger** [comment]
Took me a while but the problem was somehow related to a corrupted python environment (using a virtual env). No clue how it was messed up. Sorry for the noise....
