### ISSUE TITLE
Release failed: Current git working branch has local changes

### ISSUE THREAD

**Issue by davetcoleman** [ros-infrastructure/bloom#398]
Moved from https://github.com/ros-infrastructure/bloom/issues/300#issuecomment-238432381

I'm getting the following error when I try to release a package. I thought it might be because I just upgraded to git 2.9.2 but @wjwwood failed to reproduce the issue with that version of git.

```
Releasing 'rviz_visual_tools' using release track 'indigo'
==> git-bloom-release indigo

++ git status:

On branch master
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)
nothing to commit, working tree clean
Current git working branch has local changes
Release failed, exiting.
```

I tried again today and the issue still persists. I've double checked that following things, let me know what else I should check...

- I want to release 2.3.1 of rviz_visual_tools for indigo. 
- It is the [latest commit](https://github.com/davetcoleman/rviz_visual_tools/commits/indigo-devel) for that branch 
- A [release tag](https://github.com/davetcoleman/rviz_visual_tools/releases) exists for it
- I disabled 2-step authentication to skip that other problem
- I'm using the command ``bloom-release rviz_visual_tools --track indigo --rosdistro indigo``

I don't understand how I can have local commits in a tmp repo that was just cloned (``Cloning into '/tmp/tmpDvaGkz'...``). What is this trying to tell me?

**Comment by wjwwood** [comment]
Hmm, not sure. I'll try to reproduce it again as soon as I have time. It might help if you post your entire log output from that run in a gist.github.com. The log should be somewhere in `~/.bloom_logs` and it will contain the debug logging output as well.

**Comment by davetcoleman** [comment]
https://gist.github.com/davetcoleman/f43bb7735b11c4d02f354f350da58f83

**Comment by rohbotics** [comment]
Any updates on this issue?

I'm seeing the same issue on git 2.9.3.

**Comment by rohbotics** [comment]
Looks like git changed its output from 'working directory clean' to 'working tree clean'.

I made a PR that allows me to release, https://github.com/ros-infrastructure/bloom/pull/404.

**Comment by wjwwood** [comment]
Thanks, I don't know why I couldn't reproduce it. Maybe I had an old version of git lying around when I was testing.

**Comment by rohbotics** [comment]
I was wondering if there is any reason that we don't use libgit2/pygit2 for interfacing with git repos? It would help prevent problems like this in the future :)

**Comment by wjwwood** [comment]
@rohbotics I believe, IIRC, that both of those had really old versions in Lucid (when I originally developed bloom) and I didn't want to bundle them into bloom. Also, there were some operations that were either not possible with those libraries or were much more complicated to do with those libraries (the git cli batches some operations nicely for you).

It certainly might be worth looking at that decision again, if we ever spend a lot of time on this in the future. Mostly it's just that changing it would be a good deal of work.

**Comment by rohbotics** [comment]
That makes sense, I was just wondering.

It might make sense to switch if bloom needs a separate ROS2 version.

**Comment by wjwwood** [comment]
The plan is to use the same version of bloom for ROS 2, but we may need to spend sometime on it. That might be an appropriate time to consider this, though I'm not convinced that it would be worth the time.
