### ISSUE TITLE
bloom generating control files for EOL distros

### ISSUE THREAD

**Issue by mikaelarguedas** [ros-infrastructure/bloom#422]
Now that the ROS buildfarm doesn't build binaries for EOL distros: should bloom keep generating control files for them?
Here is how I interpret it, @ros-infrastructure/ros_team  please feel free to fill in the blanks in the following description and give your opinion about it.

Yes:
 - Pros: people can keep building debian packages for these packages easily
 - Cons: keep rosdep keys satisfied for EOL distros

No:
 - Pros:
   - save user time every time they run bloom
   - no need to worry about rosdep keys for EOL distros
 - Cons: 
   - users have to create / generate control files before being able to build debs

If yes is the choice, I think it should be documented somewhere that rosdep rules for EOL distros should be kept up to date to allow users to build their own debs.
If no: nothing specific to do, just saving time at each release and rosdep maintainance

**Comment by dirk-thomas** [comment]
> Yes: Cons: keep rosdep keys satisfied for EOL distros

Just to clarify: they could be provided by be empty. That allows bloom to pass but doesn't work when trying to build the package on an EOL distro.

**Comment by tfoote** [comment]
I'd say yes. We don't have a specific policy for older rosdep keys but we should at least keep them around long enough that bloom will no longer be being run on an active rosdistro. These rules also effect people building from source. Removing them or blanking them would break building from source.

**Comment by mikaelarguedas** [comment]
I agree with that statement. I was more referring to new keys that don't have an equivalent in the EOL distros: e.g. https://github.com/ros/rosdistro/pull/14370/files

I'm not advocating for one or the other though, I think it's ok to not enforce keeping rosdep up-to-date for EOL distros if the package was never intended to be packaged on that distro.

**Comment by jack-oquin** [comment]
I would say yes, with perhaps some restrictions. I see no problem with keeping old rosdep keys for EOL distros, but suggest making it a rule not to add new ones. 

 * allows people to maintain their own build farms and continue building old package versions
 * may prevent back-porting some new packages to EOL distros.

**Comment by dirk-thomas** [comment]
> but suggest making it a rule not to add new ones.

That is not possible if we keep blooming for EOL Ubuntu distros. `bloom` requires the used rosdep keys to be mappable for all platforms listed for the distribution. So if we choose "Yes" new rosdep keys *must* be added for EOLed distros. If the platform specific packages exist they should for sure be added (to make it work) but if they don't exist and empty list must be added (which will let bloom pass even though the package wouldn't work for that EOLdistro).

**Comment by jack-oquin** [comment]
To rephrase, my suggestion is:

 * _allow_ bloom to create packages requiring *no* new rosdeps
 * _disallow_ releasing packages to EOL distro if they need new rosdeps not already provided

Is that clearer?

**Comment by dirk-thomas** [comment]
Let's consider the different use cases in detail:

* Someone wants to keep building Debian packages for EOL distros on a custom buildfarm:

  * Since anytime a new release can be made into the official rosdistro file which doesn't work on EOL distros anymore (which was already requested in the last year a few times) this custom buildfarm **must** use a forked rosdistro since it needs to lock the old version of the package.

  * Newer releases which do work for the EOLed distros could be easily referenced in such a rosdistro fork if they are continued to be created by bloom. So choosing "yes" makes it easier for forked rosdistros to stay "close" to upstream.

  * The main question is how many custom buildfarm are actually targeting an EOL distro? From my experiences entities running their own infrastructure tend to only target LTS distros.

* Someone wants to keep building from source on an EOL distro:

  * Having rosdep keys mapped for EOL distros is certainly useful for this. If they are mappable I would advocate that they should be added. But in the case where they are not (e.g. the Debian package doesn't exist in that distro) the rosdep could either be left out or be empty.

    * Empty rosdep: even though `rosdep` will pretend it worked the build will likely fail due to missing dependencies.

    * Missing rosdep: when the user calls `rosdep` and error message will tell that. From a user point of view I think this is preferable over the previous bullet (fail-late-on-build).

    * Wrong rosdep mapping: when the user calls `rosdep` and error message will tell that the specified package isn't found. From a user point of view that error case is not great because he doesn't know why it failed.

    * The lack of functionality in rosdep hits us back here again: if a new Debian package was added in e.g. Xenial (which never existed before) it is more convenient to add a generic entry to rosdep than adding it for xenial and every future Ubuntu distro manually (every half year adding the newer platform). So it will be common that a rosdep key exists which doesn't work on older (EOL) distros. If rosdep would support a rule like "xenial-and-newer" it would be easy to achieve the second bullet without requiring continuously having to add new mapping for future platforms.

* Someone making releases (already described in the "no" block of the original description).

**Comment by dirk-thomas** [comment]
>  _allow_ bloom to create packages requiring *no* new rosdeps
> _disallow_ releasing packages to EOL distro if they need new rosdeps not already provided

The second case is the tricky one. At the moment `bloom` doesn't know which distros it is allowed to drop if there are no rosdep mappings and which distros it must satisfy for a release. It only "knows" this list of platforms for a specific ROS distro: https://github.com/ros/rosdistro/blob/ed3c6e0718c7f23e26822e5c74b6a3a14ca37eee/lunar/distribution.yaml#L5-L13

**Comment by jack-oquin** [comment]
Attempting to summarize the details above:

* ``rosdep`` does not always know which platforms actually work with a given key
* so, ``bloom`` may not always be able to tell that some EOL distros won't work

But, 

* building the originally released sources of an EOL distro *should* work

Right?

**Comment by dirk-thomas** [comment]
> building the originally released sources of an EOL distro should work, Right?

Yes, **but** there is no easy way to fetch the last "working" release for an EOL distro. The version number in the distribution file only references the latest release.

**Comment by jack-oquin** [comment]
> > building the originally released sources of an EOL distro should work, Right?

> Yes, but there is no easy way to fetch the last "working" release for an EOL distro. The version number in the distribution file only references the latest release.

Wait! The distribution file for an EOL distro no longer contains the versions that were released there? That doesn't seem right.

What about the corresponding bloom track?

**Comment by dirk-thomas** [comment]
> Wait! The distribution file for an EOL distro no longer contains the versions that were released there? That doesn't seem right.

The `distribution.yaml` in the `rosdistro` repo stores only the currently released version number. Not a history of previous releases.

> What about the corresponding bloom track?

The release repository contains all past releases unmodified. A user can always get it but that requires manual digging for the latest release available for an EOL Ubuntu distro.

**Comment by jack-oquin** [comment]
> The ``distribution.yaml`` in the ``rosdistro`` repo stores only the currently released version number. Not a history of previous releases.

So, what you're saying the problem is that some of the entries here contain ``HEAD`` or ``master`` rather than a specific tag or branch?

 * https://github.com/ros/rosdistro/blob/master/groovy/distribution.yaml

**Comment by dirk-thomas** [comment]
> So, what you're saying the problem is that some of the entries here contain HEAD or master rather than a specific tag or branch?

No, we are only talking about releases here. And releases are always identified by the version number pointing to tags in the release repo.

**Comment by jack-oquin** [comment]
Actually, we are talking about releases *and* distros.

**Comment by jack-oquin** [comment]
Are you claiming that there is no way to determine what package versions were last released to a given distro?

If so, that seems foolish.

**Comment by mikaelarguedas** [comment]
I think we have a confusion between OS and ROS distributions in this discussion.
You can find what is the latest version of a package for a given ROS distribution by looking at the `distribution.yaml` file. This doesn't provide any information about the OS distribution.

To know the latest version of a package "released" in a given Ubuntu distribution, we need to make sure about what we mean by released. If released means "built by the buildfarm", one could look up the version of the latest binary package created by the buildfarm for this OS.
If released means "bloomed", well it's going to be the same as the one in the distribution file because blooms generates control file for all distros if we chose the YES option.

In both cases there is no indication of what is the latest "working version" of a package beyond the last build provided by the buildfarm for that platform. 

At that points it gets back to "what are the use cases YES would cover?" (decribed in https://github.com/ros-infrastructure/bloom/issues/422#issuecomment-292578705) and how many users would actually benefit from the added complexity?

**Comment by mikaelarguedas** [comment]
After discussion we decided to stop blooming for EOL Ubuntu distros given that the use cases supported were few and that the amount of work required for people wanting to build themselves (and run their own buildfarm for EOL distros) is important and will not be much impacted by this change.

**Comment by mikaelarguedas** [comment]
this change has been done in https://github.com/ros/rosdistro/pull/14517, closing this
