### ISSUE TITLE
Invalid metapackage CMakeLists.txt

### ISSUE THREAD

**Issue by jlack1987** [ros-infrastructure/bloom#423]
I'm experimenting with using bloom to release my catkin package and have hit a blocker. During the release I get the following error,

```
==> git-bloom-generate -y rosrelease kinetic --source upstream -i 0
Invalid metapackage:
  Metapackage 'rdl': Invalid CMakeLists.txt
Expected:
<<<cmake_minimum_required(VERSION 2.8.3)
project(rdl)
find_package(catkin REQUIRED)
catkin_metapackage()>>>
Got:
<<<cmake_minimum_required(VERSION 2.8.3)
project(rdl)
find_package(catkin REQUIRED)
catkin_metapackage()
>>>

Refusing to release invalid metapackage 'rdl', metapackage requirements:
```

I have seen and read [this issue](https://github.com/ros-infrastructure/catkin_pkg/issues/56) that appears to be having the same exact problem, but I do not have any extra whitespaces or anything in my file. Based on the message it looks like it thinks there's a line return at the end of the file, putting the `>>>` on the next line at the end, but I do not have a line return at the end. I have attached the [CMakeLists.txt](https://github.com/ros-infrastructure/bloom/files/929059/CMakeLists.txt) file that it is complaining about.

**Comment by tfoote** [comment]
Can you try adding a newline after the `catkin_metapackage()` call? The intermediate might be being compared to the original in an ambiguous order.

**Comment by jlack1987** [comment]
Tried it and got the exact same error

**Comment by jlack1987** [comment]
Does it matter that my project is hosted on ```GitLab``` and not ```GitHub```?

**Comment by jlack1987** [comment]
Got it working. It was the newline at the end of the file. I guess in previous testing when I thought i'd fixed it and it still broke I hadn't actually fixed it somehow.
