### ISSUE TITLE
apt.py conflicts with system apt

### ISSUE THREAD

**Issue by miquelmassot** [ros-infrastructure/bloom#430]
Please read https://askubuntu.com/questions/928048/software-properties-gtk-crashes-on-ubuntu-16-04-startup

**Comment by tfoote** [comment]
This was filed: https://github.com/ros-infrastructure/ros_buildfarm/issues/456 and resolved: https://github.com/ros-infrastructure/ros_buildfarm/pull/457

It looks like it needs a new release to propogate. @dirk-thomas is expecting to make a new release soon pending resolving an open issue.
