### ISSUE TITLE
oauth token only used sometimes during bloom-release

### ISSUE THREAD

**Issue by jarvisschultz** [ros-infrastructure/bloom#436]
This could possibly be related to #256, which doesn't seem to have been properly resolved. I just released a package with two-factor on, and a freshly created oauth token in my `~/.config/bloom` file. For many of the early steps in the `bloom-release` I was asked to type in my username and password. E.g.
```
==> Pushing changes to release repository for 'python_trep'
==> git push --all
Username for 'https://github.com': jarvisschultz
Password for 'https://jarvisschultz@github.com':
```
I only was able to continue by pasting in the oauth token each time I needed a password. However, on the last step when the PR was opened on the rosdistro repo, it did not ask for a username and password, and it successfully used my oauth token (obvious because the oauth token was printed to stdout, just like in #411):
```
Open a pull request from 'rosdistro/rosdistro:bloom-python_trep-1' into 'ros/rosdistro:master'?
Continue [Y/n]?
==> git checkout -b bloom-python_trep-1
Switched to a new branch 'bloom-python_trep-1'
==> Pulling latest rosdistro branch
remote: Counting objects: 102504, done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 102504 (delta 6), reused 14 (delta 3), pack-reused 102485
Receiving objects: 100% (102504/102504), 30.69 MiB | 2.09 MiB/s, done.
Resolving deltas: 100% (66218/66218), done.
From https://github.com/ros/rosdistro
 * branch            master     -> FETCH_HEAD
==> git reset --hard 3268abec1b62871b3307a97285a6472aeacf61cd
HEAD is now at 3268abe Merge pull request #16012 from jarvisschultz/bloom-python_trep-0
==> Writing new distribution file: kinetic/distribution.yaml
==> git add kinetic/distribution.yaml
==> git commit -m "python_trep: 1.0.3-1 in 'kinetic/distribution.yaml' [bloom]"
[bloom-python_trep-1 2788df9] python_trep: 1.0.3-1 in 'kinetic/distribution.yaml' [bloom]
 1 file changed, 15 insertions(+)
==> Pushing changes to fork
Counting objects: 5, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (4/4), done.
Writing objects: 100% (5/5), 782 bytes | 0 bytes/s, done.
Total 5 (delta 2), reused 1 (delta 0)
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To https://a4d8695027953207e1927aa1af52c8d808706b1f:x-oauth-basic@github.com/jarvisschultz/rosdistro.git
 * [new branch]      bloom-python_trep-1 -> bloom-python_trep-1
<== Pull request opened at: https://github.com/ros/rosdistro/pull/16013
```
Any idea why the config file would be ignored for some of the git commands, but not others?

**Comment by wjwwood** [comment]
Somethings cannot use the oauth token directly. For those you need to authenticate normally and since you're using https it asks (that's why it asks for your username and password). I recommend using the `insteadOf` so that https is converted to ssh and it uses your ssh keys rather than plain authentication. See:

https://github.com/ros-infrastructure/bloom/issues/256#issuecomment-214927775

**Comment by jarvisschultz** [comment]
Fair enough... thanks for such a fast response.
