### ISSUE TITLE
Bloom-Generate error 

### ISSUE THREAD

**Issue by ozweigle** [ros-infrastructure/bloom#439]
Ubuntu Version 16.04.
Bloom-Version: Master branch

Call of bloom-generate: 
bloom-generate rosdebian -d --os-name ubuntu --os-version xenial --ros-distro kinetic

The latest version seems to have a bug with a missing parameter in 
- bloom/generators/debian/generate_cmd.py

Function calls of 
- place_template_files(path)
- Line 129, Line 136
 
have a missing parameter. The template argument is not given. bloom-generate will crash with the following debug message:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/bloom-0.6.0-py2.7.egg/bloom/generators/debian/generate_cmd.py", line 136, in main
    place_template_files(path)
TypeError: place_template_files() takes at least 2 arguments (1 given)

**Comment by kmhallen** [comment]
I get the same error with ```bloom-generate rosdebian``` after the latest ```apt-get``` update

**Comment by nuclearsandwich** [comment]
This is likely an issue due to the internal API changes from #435 that the unit tests didn't cover. I'll work on a fix today. In the meantime, using pip or git to pull the 0.5.26 version is the recommended workaround.

`pip install bloom==0.5.26`

**Comment by kmhallen** [comment]
For those unfamiliar with ```pip``` and ```virtualenv```, the sequence of commands below worked for me:
```
sudo apt-get install virtualenv python-pip
virtualenv env
source env/bin/activate
pip install bloom==0.5.26
```

**Comment by nuclearsandwich** [comment]
Thanks for the initial report @ozweigle and as a maintainer I'd like to double thank you for working from Bloom's master branch. We coordinated this release with the functionality that introduced this regression but in general folks like you help us catch regressions before they make it into a release which is extremely valuable.

If you would like to try out the branch from #440 it should address this issue. 

@kmhallen thanks for the more thorough workaround instructions. I'm sure those will help some folks who might be using bloom via pip for the first time.

**Comment by nuclearsandwich** [comment]
bloom 0.6.1, which includes a fix for this issue, has been released and pushed out. The apt repositories are syncing now so python-bloom and python3-bloom should install version 0.6.1 the next time you update.

If you installed 0.5.26 via pip you can update it by running `pip install --update bloom`. If you used a virtualenv as suggested by @kmhallen's instructions you will need to activate the virtualenv before doing so.

If you wish to remove the pip-installed version you can do so with `pip uninstall bloom`. There will be a prompt to confirm, answer `y`.

If you installed bloom in a virtualenv that is no longer needed, you can run the command `deactivate` to make sure you leave the virtualenv. The command may not exist if you did not first activate it.
Then delete the virtualenv directory (called `env` in kmhallen's instructions).

**Comment by kmhallen** [comment]
Works for me. Thanks for the quick fix.

**Comment by ozweigle** [comment]
Thanks for the quick fix! I have patched it myself for the last two days on the build server. Now I can go back to the apt version. Great!
