### ISSUE TITLE
ascii encoding error running catkin_prepare_release

### ISSUE THREAD

**Issue by facontidavide** [ros-infrastructure/bloom#447]
I am having an issue very similar to #410, but running  catkin_prepare_release

I don't really know which is the "offending" character...
https://github.com/facontidavide/PlotJuggler/blob/master/CHANGELOG.rst

UPDATE: https://github.com/facontidavide/PlotJuggler/commit/ae013485c87db19081be1a370bea4c871f6132a9

I found them, but for your information, this didn't use to fail...

**Comment by 130s** [comment]
I believe software-wise that `catkin_prepare_release` isn't a part of `bloom`. Instead it should be reported in catkin and I just opened https://github.com/ros/catkin/issues/901
