### ISSUE TITLE
AttributeError: get_build_type

### ISSUE THREAD

**Issue by arnasIV** [ros-infrastructure/bloom#449]
Whenever I am in a ROS package folder and try to run:

> bloom-generate rosdebian --ros-distro kinetic

I get the following output:

> ==> Generating debs for ubuntu:xenial for package(s) ['camera_info_manager']
> AttributeError: get_build_type

No explanation given, does not matter the package. Could not find this issue anywhere else.

**Comment by wjwwood** [comment]
Make sure you have an up-to-date version of `catkin_pkg`, but if that's not it, then it might be something related to the ROS 2 support we've been working on. @nuclearsandwich?

**Comment by nuclearsandwich** [comment]
@arnasIV What version of bloom are you running and how was it installed? Also what is your host platform/OS?

 @wjwwood is correct that you should need a relatively recent catkin-pkg for current bloom
https://github.com/ros-infrastructure/bloom/blob/c40ab07609e199b13c4088cdb03f9c1071c4f900/setup.py#L7

**Comment by arnasIV** [comment]
Ubuntu 16.04 LTS arm64
`apt` show python-catkin-pkg

> Package: python-catkin-pkg
> Version: 0.3.9-100
> Priority: optional
> Section: python
> Maintainer: Dirk Thomas <dthomas@osrfoundation.org>
> Installed-Size: 22.5 kB

`apt` show python-bloom

> Package: python-bloom
> Version: 0.6.1-1
> Priority: optional
> Section: python
> Maintainer: William Woodall <william@osrfoundation.org>
> Installed-Size: 482 kB
>

**Comment by nuclearsandwich** [comment]
Glad to hear it. I'm going to close this issue but please re-open it if you feel there's an unaddressed need.
