### ISSUE TITLE
Support debian copyright file

### ISSUE THREAD

**Issue by otamachan** [ros-infrastructure/bloom#456]
Hi,
I'm not sure here is the right place to raise this issue, but I think ``bloom`` is the related tool, so I'm posting it here. 
Some OSS licenses such as BSD and MIT require provision of license and copyright text when a user redistribute the software in a source or binary form. Debian packaging system do this by installing ``copyright`` file under ``/usr/share/doc/package-name/`` when the binary package is installed. I would appreciate ``bloom`` supports this feature so that it generates ``copyright`` file under ``debian`` folder in some way. I think this can be done by adding a command line option to ``bloom`` or changing ``package.xml`` format to point the copyright file(ex. ``<license file="LICENSE.txt">BSD</license>``).

Thanks in advance.

**Comment by wjwwood** [comment]
Thanks for posting the suggestion. We probably don't have time to implement it right now, but it sounds like a reasonable thing to do (though your `<license file="..."...` syntax would require a change to the `package.xml` format (http://www.ros.org/reps/rep-0140.html) which is controller through the REP process (http://www.ros.org/reps/rep-0000.html).

If you'd like to see this feature in bloom, the best way will be to provide a pull request, though we can try to help with guidance and answering questions.

**Comment by otamachan** [comment]
Thanks for your feedback. I found a REP-149(https://github.com/ros-infrastructure/rep/blob/master/rep-0149.rst), which is still a draft, so I will propose a revise of the license tag there.

**Comment by nuclearsandwich** [comment]
This has been released in bloom 0.6.7 #488
