### ISSUE TITLE
How do I bloom an untagged commit?

### ISSUE THREAD

**Issue by rethink-neil** [ros-infrastructure/bloom#482]
Both the [First Time Release](http://wiki.ros.org/bloom/Tutorials/FirstTimeRelease) and [Release Third Party](http://wiki.ros.org/bloom/Tutorials/ReleaseThirdParty) tutorials describe how to prepare tagged commits within the "upstream" repository. The page at https://bloom.readthedocs.io/ mentions this specifically (even though the notion of tags is specific to git while `bloom-release` supports other kinds of upstream things.

I'm trying to bloom an upstream git repository and the commit I want to release does _not_ have a tag. I would prefer that the version string follow the `git describe --long --always --tags`, but at this point I'll take what I can get?

Is what I describe possible with `bloom-release` in its current form?

**Comment by rethink-neil** [comment]
@mikaelarguedas , neat! It looks like passing the value of...

    $ git -C path/to/upstream-checkout rev-parse "origin/${upstream_devel_branch}"

...to `bloom-release` for the `release_tag` field is actually working as intended. Passing the value of...

    $ git -C path/to/upstream-checkout describe --long --always --tags "${release_tag}"

...to `bloom-release` for the `version` field gives this:

    Traceback (most recent call last):
      File "/usr/bin/bloom-release", line 9, in <module>
        load_entry_point('bloom==0.6.6', 'console_scripts', 'bloom-release')()
      File "/usr/lib/python2.7/dist-packages/bloom/commands/release.py", line 1341, in main
        args.override_release_repository_push_url)
      File "/usr/lib/python2.7/dist-packages/bloom/commands/release.py", line 1224, in perform_release
        tracks_dict = create_a_new_track(track, tracks_dict)
      File "/usr/lib/python2.7/dist-packages/bloom/commands/release.py", line 1219, in create_a_new_track
        tracks_dict = get_tracks_dict_raw()
      File "/usr/lib/python2.7/dist-packages/bloom/config.py", line 277, in get_tracks_dict_raw
        validate_track_versions(tracks_dict)
      File "/usr/lib/python2.7/dist-packages/bloom/config.py", line 261, in validate_track_versions
        .format(track['version']))
    ValueError: Invalid version '1.11.8-10-ge9bf8dc', it must be formatted as 'MAJOR.MINOR.PATCH'

Is there any way to force `bloom-release` to swallow a version string that's not a dotted-triplet?

**Comment by wjwwood** [comment]
Where does the `package.xml` come from? Is it in the repository you're releasing or in a "patch folder" in the release repository? The `:{version}` token will only be replaced if it's a patch applied to upstream.

**Comment by mikaelarguedas** [comment]
> Is there any way to force bloom-release to swallow a version string that's not a dotted-triplet?

Not that I know of. 

> update: passing a fake version 42.42.42 gets me a little farther. Now I can see it die like this:

Could you provide the full console output as well as confirming where your `package.xml` file is located?
Is your package.xml located in your source repository or release repository ?

**Comment by rethink-neil** [comment]
Here's the commit to the "upstream" repository wherein I've rewritten (from the branch `indigo-rethink`) all the `package.xml` files to have the `:{version}` template symbol:

https://github.com/rethink-neil/ros_comm/commit/e9bf8dc378dbf8c12b35e6c408ff62967443971e

**Comment by mikaelarguedas** [comment]
Ok that's where the misunderstanding come from. Templating the package.xml is for repos where you *don't* have access to the source repository and provide the package.xml / patch it in the release repository.

In your case you do have access to the source repo.
Could you clarify the reason for *not* tagging your commit as a new version and release that new version?
Otherwise you can just pass the commit to the `release_tag` field as mentionned above and use the version number that is already present in the `package.xml`. But we would recommend to tag a new version pointing to the commit you want to release

**Comment by rethink-neil** [comment]
The reason for not tagging the `HEAD` of the `${upstream_devel_branch}` is that the branch is old, and it's impossible (for me) to pick a tag that -- within the context of official and forked repositories -- won't collide with existing (or forthcoming) tags.

To take the example presented here, I can't simply tag `indigo-rethink` with a patch-level bump (to `1.11.9`): that tag already exists (on the `kinetic-rethink` branch).

**Comment by tfoote** [comment]
@rethink-neil You can always jump several patch numbers ahead.  And if you have forked development you should probably jump to a new minor for kinetic. (or you could jump to a new minor for indigo (multiple higher) if kinetic would cascade into lunar and melodic series.

I think you'll find that release numbers are cheap and custom code paths take way more of your time.

**Comment by rethink-neil** [comment]
@mikaelarguedas , duly noted. I was able to hack together something that's close to what I want. It involves lying to `bloom-release` about the version string -- just to get a release repository. After that, for each branch therein, I `gbp dch --new-version=${desired_version}` just before the invocation to `gbp buildpackage`. The OSRF-faithful would probably hate it, but it's working for me.
