### ISSUE TITLE
GitHub exception: ==> Failed to open pull request: KeyError - 'packages'

### ISSUE THREAD

**Issue by machinekoder** [ros-infrastructure/bloom#497]
I'm getting following error: `==> Generating pull request to distro file located at 'https://raw.githubusercontent.com/ros/rosdistro/2c4d99f05d0081640da7708b58dfcb79268b4bae/kinetic/distribution.yaml'
Failed to open pull request: KeyError - 'packages'`
When trying to release a package.

Looks similar to https://github.com/ros-infrastructure/bloom/issues/294 but I already cleaned up my rosdep fork.

**Comment by machinekoder** [comment]
The command I used: `bloom-release ros_pytest --rosdistro melodic` and `bloom-release ros_pytest --rosdistro kinetic`

**Comment by nuclearsandwich** [comment]
@machinekoder If you're using bloom from python3 this is a long outstanding bug. I'd be very grateful if you gave the branch in #489 a try. I've just rebased it onto the latest 0.6.9 release of bloom but I haven't tested it since doing so :worried:

**Comment by machinekoder** [comment]
I tested the latest master, unfortunately, there is still a problem `Failed to open pull request: NameError - name 'version' is not defined`. Went ahead with python2, worked like a charm.

**Comment by nuclearsandwich** [comment]
The later issue with `version` was fixed with #505 and released in [0.7.1](https://github.com/ros-infrastructure/bloom/releases/tag/0.7.1)
