### ISSUE TITLE
Cannot generate pull requests from Bloom

### ISSUE THREAD

**Issue by samuelba** [ros-infrastructure/bloom#499]
I cannot open a pull request in rosdistro with Bloom anymore. I get the following error: 

```
Unified diff for the ROS distro file located at '/tmp/tmpFsT4Il/rqt_multiplot_plugin-0.0.8-1.patch':
--- melodic/distribution.yaml
+++ melodic/distribution.yaml
@@ -4739,6 +4739,14 @@
       url: https://github.com/ros-visualization/rqt_msg.git
       version: master
     status: maintained
+  rqt_multiplot_plugin:
+    release:
+      packages:
+      - rqt_multiplot
+      tags:
+        release: release/melodic/{package}/{version}
+      url: https://github.com/anybotics/rqt_multiplot_plugin-release.git
+      version: 0.0.8-1
   rqt_nav_view:
     doc:
       type: git
<string>:52: (WARNING/2) Bullet list ends without a blank line; unexpected unindent.
<string>:71: (WARNING/2) Bullet list ends without a blank line; unexpected unindent.
==> Checking on GitHub for a fork to make the pull request from...
Could not find a fork of ros/rosdistro on the samuelba GitHub account.
Would you like to create one now?
Continue [Y/n]? 
Aborting pull request: HTTP Error 401: Unauthorized (https://api.github.com/repos/ros/rosdistro/forks)
The release of your packages was successful, but the pull request failed.
Please manually open a pull request by editing the file here: 'https://raw.githubusercontent.com/ros/rosdistro/master/melodic/distribution.yaml'
<== No pull request opened.
```

What I tried already:
- Remove my clone and create a new clone of rosdistro -> still not working (my clone https://github.com/samuelba/rosdistro)
- Use a token (full access rights) as described here http://wiki.ros.org/bloom/Tutorials/GithubManualAuthorization -> not working
- Modify the .gitconfig to force ssh -> not working

I use two factor authentication on Github, but with a token or ssh it should still work, right?

Is there something else I can try?

**Comment by nuclearsandwich** [comment]
The forks API method doesn't require authorization, so the 401 suggests the token bloom is trying to use isn't validating.

If you copy the token from your bloom config and run the command below, replacing `$GITHUB_USERNAME` and `$GITHUB_TOKEN` with your username and token it might reveal an issue with the configured token.

`curl -u "$GITHUB_USERNAME:$GITHUB_TOKEN" 'https://api.github.com/user'`

Running bloom-release with the `--debug` and `--pull-request-only` flags will let you try to re-run the pull request creation without creating a new release.

**Comment by samuelba** [comment]
Ok, my bad, I had an old token in the file `~/.config/bloom`, but used a new token in the steps before the pull request, so I thought the token is working but it wasn't.

Thanks for your help.
