### ISSUE TITLE
How is overwriting the debian folder supposed to work?

### ISSUE THREAD

**Issue by mistoll** [ros-infrastructure/bloom#507]
I'm trying to replace the debian/rules.em file with a custom file. How is this supposed to work?

I tried to place a debian folder in the source repository, but it gets overwritten in the debian/* branches of the release repository.

This code seems to handle that:

https://github.com/ros-infrastructure/bloom/blob/54a41a0e773868a7e48f574af06836a19ecb7a3a/bloom/generators/debian/generator.py#L821-L841

I'm getting the message 
> Not overwriting debian directory.

However the directory is overwritten anyway

**Comment by nuclearsandwich** [comment]
@mistoll this is functionality that I've not yet touched so it'll take me a while to onboard to it fully. Is the repository you're releasing something you can share a link to?

**Comment by mistoll** [comment]
@nuclearsandwich 
It's a private repository, but I can share relevant parts of it. Let me explain a bit, what this is about. The reopository contains a custom pcb, a firmware for the microcontroller on that pcb and a ROS driver. This issue is about the firmware, which is compiled using gcc-avr. That works fine with `catkin build`. However when it's build using `apt-src build` the hardening flags, especially stack-protector, break the build, because gcc-avr does not support them.

Back to bloom. Maybe, if nobody else is using or needing this feature, you shouldn't support it at all. However there's still https://github.com/ros-infrastructure/bloom/blob/54a41a0e773868a7e48f574af06836a19ecb7a3a/bloom/generators/debian/generator.py#L836
I'm not into bloom deep enough to estimate the impact of that line. But maybe a solution could be as simple as:
```
else: 
    warning("Not overwriting debian directory.")
    return
```
I'll give it a try. Would you accept a PR for something like that?

**Comment by nuclearsandwich** [comment]
> I'll give it a try. Would you accept a PR for something like that?

On the surface that seems a reasonable starting point. Also the fact that there's no way to skip placing the template files when bloom is in interactive mode https://github.com/ros-infrastructure/bloom/blob/54a41a0e773868a7e48f574af06836a19ecb7a3a/bloom/generators/debian/generator.py#L824-L836 without exiting the program.

**Comment by wjwwood** [comment]
I haven't followed this issue completely, but the idea was that if you have a file in your repository like `debian/rules.em` then bloom will not place it's own template file. If you want a static `debian/rules` file, then just name it as `.em` and no substitution will occur.

**Comment by mistoll** [comment]
If we want single files so be replaceable, we should look at:
https://github.com/ros-infrastructure/bloom/blob/54a41a0e773868a7e48f574af06836a19ecb7a3a/bloom/generators/debian/generator.py#L149-L151

Any file in the debian directory will be overwritten. So idea of @wjwood wont work, however placing additional files, like @mikepurvis did works.

Here's some output of git-bloom-generate which proves, that the lines above are hit:
```
Not overwriting debian directory.
==> Placing templates files in the 'debian' folder.
Recursing on folder 'templates/catkin/source'
Placing template 'templates/catkin/source/format.em'
Removing existing file './debian/source/format.em'
Placing template 'templates/catkin/source/options.em'
Removing existing file './debian/source/options.em'
Placing template 'templates/catkin/rules.em'
Removing existing file './debian/rules.em'
Placing template 'templates/catkin/compat.em'
Removing existing file './debian/compat.em'
Placing template 'templates/catkin/copyright.em'
Removing existing file './debian/copyright.em'
Placing template 'templates/catkin/control.em'
Removing existing file './debian/control.em'
Placing template 'templates/catkin/gbp.conf.em'
Removing existing file './debian/gbp.conf.em'
Placing template 'templates/catkin/changelog.em'
Removing existing file './debian/changelog.em'
```

This (https://github.com/mistoll/bloom/commit/cf62c795434f85ce32840c6bb214a1ba369dad35) should implement the intended behavior. However is there any circumstance, where we want to actually overwrite a file?

**Comment by nuclearsandwich** [comment]
> However is there any circumstance, where we want to actually overwrite a file?

If the in-source file is for Debian rather than Ubuntu or vice versa and our bloom templated file is generic that could be a reason to prefer the bloom-provided template, but maintainers should still have the option to patch or patch out their in-source templates before bloom checks. This PR does change behavior even if it doesn't change documented intention.

**Comment by mistoll** [comment]
From my point of view this order makes sense:
1. Use bloom templates (current default)
2. Use source-files if they exist (implemented in #516)
3. Allow package maintainer to overwrite anything

The last one is most important. It addresses the issues described in the previous post (https://github.com/ros-infrastructure/bloom/issues/507#issuecomment-481686791). Also with 3 there would be less need for 2.

I don't know enough about bloom to know if and how 3 could work. There are two related commits in the release repository: 'Placing debian template files' and 'Generated debian files for ...'. Is it possible to apply patches between those?

**Comment by nuclearsandwich** [comment]
> From my point of view this order makes sense:
> 
>     1. Use bloom templates (current default)
> 
>     2. Use source-files if they exist (implemented in #516)
> 
>     3. Allow package maintainer to overwrite anything

Wouldn't

1. Use source files if they exist
2. Use bloom templates if they don't

Give the package maintainer the ability to overwrite anything by adding it to the source repo or the appropriate template branch (see below).



> There are two related commits in the release repository: 'Placing debian template files' and 'Generated debian files for ...'. Is it possible to apply patches between those?

Yes. The [Changing default build flags](https://wiki.ros.org/bloom/Tutorials/ChangeBuildFlags) tutorial covers making modifications to the templates after they're committed to the release repository but before they're evaluated for the next release.

**Comment by nuclearsandwich** [comment]
I'm going to merge #516 in order to include it in the 0.8.0 release.

**Comment by mistoll** [comment]
> 1.  Use source files if they exist
> 2.  Use bloom templates if they don't
That's exactly what I meant (comment updated)

**Comment by nuclearsandwich** [comment]
> > 2\.
> 
> That's exactly what I meant (comment updated)

Ah, got it. So with #516 merged you should be able to do what you need once the next bloom release is out, correct?

**Comment by mistoll** [comment]
> So with #516 merged you should be able to do what you need once the next bloom release is out, correct?

Correct.
