### ISSUE TITLE
debian generator documentation is incomplete

### ISSUE THREAD

**Issue by VictorLamoine** [ros-infrastructure/bloom#518]
Help command (https://github.com/ros-infrastructure/bloom/blob/master/bloom/generators/debian/generate_cmd.py#L64)
```bash
$ bloom-generate debian --help
usage: bloom-generate debian [-h]
                             [--place-template-files | --process-template-files]
                             [--os-name OS_NAME] [--os-version OS_VERSION]
                             [--ros-distro ROS_DISTRO] [--native] [-d]
                             [--version] [--unsafe]
                             [package_path]

Generates debian packaging files for a catkin package

positional arguments:
  package_path          path to or containing the package.xml of a package

optional arguments:
  -h, --help            show this help message and exit
  --place-template-files
                        places debian/* template files only
  --process-template-files
                        processes templates in debian/* only
  --os-name OS_NAME     OS name, e.g. ubuntu, debian
  --os-version OS_VERSION
                        OS version or codename, e.g. precise, wheezy
  --ros-distro ROS_DISTRO
                        ROS distro, e.g. indigo, kinetic, lunar, melodic (used
                        for rosdep)
  --native              generate native package

global:
  -d, --debug           enable debug messages
  --version             prints the bloom version
  --unsafe              Makes bloom faster, but if there is an error then you
                        could run into trouble.
```

However this generator seems to be able to handle more arguments, for example `--install-prefix`.
https://github.com/ros-infrastructure/bloom/blob/master/bloom/generators/debian/generator.py#L574-L592

Am I misunderstanding how the generator works or is the `--help` documentation out-of-date?

**Comment by nuclearsandwich** [comment]
The changes contributed in #526 help here but the `bloom-generate debian` subcommand doesn't have an install-prefix option, though the `bloom-generate rosdebian` subcommand [does]

As mentioned in https://github.com/ros-infrastructure/bloom/pull/526#issuecomment-481870938, the `bloom-generate ...` and `git bloom-generate ...` commands are distinct and have different sets of arguments.

To use the `--install-prefix` option you would need to use the `git bloom-generate ...` command instead.

Alternatively if you wanted to open a pull request adding support for the option, I would review it. Although I haven't checked to see if there's a reason it's not currently implemented for these commands.

I am going to close this issue, having addressed your question but please re-open it if this answer seems incomplete to you.
