### ISSUE TITLE
How to `<replace>`/`Replaces:` a non-ROS package?

### ISSUE THREAD

**Issue by rubicks** [ros-infrastructure/bloom#520]
I don't know if this is a bug or just lacking functionality...

When I do this:

    foo/package.xml:
    ...
    <replace>bar</replace>
    ...

I get this:

    $ dpkg-deb --info ros-kinetic-foo_0.1.0_amd64.deb
    ...
     Replaces: ros-kinetic-bar
    ...

What do I do if I don't want that `ros-kinetic-` prefix on the replaced package name? How do I tell a bloomed package to replace a non-ROS package?

This issue is in regards to the ROS Answers question here: https://answers.ros.org/question/317627/packagexml-use-replace-tag-for-non-ros-package/

**Comment by dirk-thomas** [comment]
There is no need to cross post the same question. Let's keep the conversation on answers.ros.org.
