### ISSUE TITLE
Generated debian/compat files end without newlines

### ISSUE THREAD

**Issue by dankamongmen** [ros-infrastructure/bloom#524]
After running `bloom-generate` across my packages, I noticed that the debian/compat files generated were lacking terminating newlines. This seems strange, so I've gone ahead and added newlines to the templates. Please merge, unless I'm missing something. Thanks!

https://github.com/ros-infrastructure/bloom/pull/523

**Comment by nuclearsandwich** [comment]
Closed by #523 and released in 0.8.0
