### ISSUE TITLE
Option to not open pull requests?

### ISSUE THREAD

**Issue by zlacelle** [ros-infrastructure/bloom#535]
Hello,

I'm using the bloom tools to release packages internally, and want them to be compatible with the ROS build farm in the future. However, currently I don't want them to open pull requests to the ROS build farm. When I run bloom-release, I don't see an option to disable this function, but in the docs it says " but if there is a problem or you do not wish for it to open the pull request on your behalf you can manually open a pull request also."

I think this may be a bug either in the docs or in the script, unless this feature does exist and I just can't find it.

**Comment by mikepurvis** [comment]
Are you setting `ROSDISTRO_INDEX_URL` in your environment? If it's pointing to a non-Github location, then the PR logic doesn't happen anyway.

**Comment by zlacelle** [comment]
Hello,

I was not setting it separately, and thus was using the default distro URL. If I set it to a garbage value, it doesn't work, so I need it set to an actual working index.yaml I assume.

Does this mean I need a correctly set up index.yaml with supporting distribution.yaml files? I want to eventually integrate this into the ROS ecosystem, and don't really want to duplicate this locally. I simply don't want to make the merge request. Everything else is great (release repository, tagging, branching, and generating packaging files).

**Comment by mikepurvis** [comment]
Not that bloom shouldn't have an option for doing what you want, but it would still be helpful to understand more about your use-case. For example:

- Without a distribution.yaml, you're only ever going to be able to bloom leaf packages— if you release a package without its dependencies listed in the distribution, bloom won't be able to resolve them (unless you do hacks like adding them to rosdep).
- Are you manually running git-buildpackage yourself against the bloom-generated gbp repos?
- There isn't a lot you have to "duplicate locally". It could be as simple as forking rosdistro into your own GH account, making it private, and using that as your `ROSDISTRO_INDEX_URL`. You'll still get the PR generated, but you can ignore it if you don't want to keep your distribution up to date with the packages you're releasing.

**Comment by zlacelle** [comment]
My goal is to use a development process internally, when preparing a package we develop for public ROS consumption, to parallel the ROS toolchain as much as possible to make future transition easy.

Additionally, ROS tools to build debians from package.xml are useful, and remove the requirement to track versions in two places if I was managing my own debuild debian/ directory. Regardless if I release packages externally, using these tools is helpful. I already have a pipeline where I utilize catkin_generate_changelog, catkin_prepare_release, and bloom-generate rosdebian to version and create debians. However, due to some oddities with Jenkins and multibranch pipelines, I like the idea of having a separate release repository that builds debians with the CI/CD tool automatically and uploads them to our Aptly server.

Finally, I just don't have a good grasp on how bloom works, and while I've read the tutorials and tried to dig through the python code, I still don't have a great hold on distribution.yaml vs index.yaml, exactly how tracks work, etc. So I could just be misusing the tools.

**Comment by nuclearsandwich** [comment]
When performing QA on bloom before releases I often point it at a forked rosdistro URL to make sure the full pull request flow is working. https://github.com/nuclearsandwich/rosdistro/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc

Setting `ROSDISTRO_INDEX_URL` to a fork will at least send PRs to yourself which can be ignored.

> Not that bloom shouldn't have an option for doing what you want

I agree that an option to skip pull requests wouldn't be a bad thing. I think that for the official rosdistro index it's much easier for us to review and merge PRs generated by bloom but as long as it remains the default for supported index hosts I would review PRs to add a skip option.

**Comment by zlacelle** [comment]
OK, I may generate a pull request for this. For now, I'm happy with this workaround.

Final note for folks who find this later: for the ROSDISTRO_INDEX_URL, you should use the raw path to the index.yaml file (in Gitlab, for instance, this would be seen by the "view raw" option). Something likek this: https://gitlab.mysite.org/rosdistro/raw/master/index.yaml
