### ISSUE TITLE
generator templates for debian using debhelper do not support parallel builds

### ISSUE THREAD

**Issue by realtime-neil** [ros-infrastructure/bloom#546]
There is no support for parallel builds in any of the four generators that target the debian platform. More exactly, the `--parallel` option to the debhelper command within the default rule is conspicuously absent for each of the following:

* `bloom/generators/debian/templates/ament_cmake/rules.em`
* `bloom/generators/debian/templates/ament_python/rules.em`
* `bloom/generators/debian/templates/catkin/rules.em`
* `bloom/generators/debian/templates/cmake/rules.em`

**Comment by nuclearsandwich** [comment]
The ROS buildfarm runs builds in a single threaded environment for deterministic progress and output. For building bloomed packages in other contexts you could patch the templates to include `--parallel`.

**Comment by realtime-neil** [comment]
> The ROS buildfarm runs builds in a single threaded environment for deterministic progress and output. For building bloomed packages in other contexts you could patch the templates to include `--parallel`.

Okay, understood. What should become of this issue and should I do anything to it?

**Comment by nuclearsandwich** [comment]
If this is something you very much want in upstream bloom then a PR to enable it optionally is the next step.

If you only have a few packages and don't change release tracks often you're probably best off just patching the templates by hand as they're fairly set-and-forget for the lifetime of a release track.

Unless you intend to follow up directly with a PR I think we can close this issue as an answered question.

**Comment by nuclearsandwich** [comment]
Closing since no follow up is needed.
