### ISSUE TITLE
The Return Of: Failed to open pull request: GithubException - Failed to create pull request: 422 Unprocessable Entity

### ISSUE THREAD

**Issue by JWhitleyAStuff** [ros-infrastructure/bloom#557]
Same exact issue as #294 but the solution provided does not fix my issue. Fork is at https://github.com/jwhitleyastuff/rosdistro. I've deleted all stale branches on my fork but continue to get the same error.

**Comment by SteveMacenski** [comment]
I am seeing this as well when I went to release Navigation2 https://github.com/ros/rosdistro/pull/23304

**Comment by JWhitleyAStuff** [comment]
@SteveMacenski - Some new information on this: It seems to be version-specific. I figured out that my primary environment where I'm seeing this issue is using Eoan and has `python3-bloom` installed from the Ubuntu repo instead of the ROS repo, which installs 0.8.0. If I instead do this in a Docker container from `ros:dashing`, it installs 0.9.0 from the ROS2 repo and works correctly. I've added the ROS2 repo to my Eoan environment and upgraded Bloom. I'll let you know if this fixes the issue (I suspect that it will).

**Comment by JWhitleyAStuff** [comment]
So, even after updating to the latest version from the ROS2 repo, I still get this error in my Eoan environment and not in the Bionic environment in `ros:dashing`. Let me know what version of Ubuntu you're seeing this issue on.

**Comment by SteveMacenski** [comment]
I know I've seen it on 18.04, but I suspect I also have seen it on 16.04, though I don't have records to confirm. It started happening to me the same day you posted this ticket. I haven't looked into it at all since I can still just open the PR and paste in the content (and the holidays / CES).

**Comment by dirk-thomas** [comment]
Can you check the `python(3)-rosdistro` version you have installed? If an update of that package resolves the problem it might related to this: https://github.com/ros-infrastructure/rosdistro/pull/147#issuecomment-573302415

**Comment by SteveMacenski** [comment]
Both python versions are 0.8.0-100 according to apt, though `bloom-release --version` tells me `0.9.0`, so I'll just go with that one assuming there's some mixup in `apt` vs `pip` installation introduced at some point on my system.

Did some upgrading and clean installs but still fails on my end.

**Comment by tfoote** [comment]
what does `pip freeze` say about your two versions? Do you have an outdated pip version overlaying your apt version?

**Comment by SteveMacenski** [comment]
`bloom 0.9.0` from `pip freeze`. Pip versions are consistent at `9.0.1`

**Comment by dirk-thomas** [comment]
@wjwwood @nuclearsandwich Please investigate the problem reported in https://github.com/ros-infrastructure/rosdistro/pull/147#issuecomment-573302415 in this context.

**Comment by wjwwood** [comment]
@SteveMacenski what command are you running exactly? If one of us can run the same command without error, then I have to conclude it is your environment which has an out of date version of the `python-rosdistro` library, even if we cannot guess how an out of date version is being used.

Note that `pip freeze` is kind of useless, because you don't know which environment `pip` is using. It's better to explicitly use a python executable to invoke pip, e.g. `python3 -m pip ...` or `python -m pip ...`.

**Comment by SteveMacenski** [comment]
Well, @JWhitleyAStuff is still having this issue as well as of his last response. 

Any advise? I uninstalled and reinstalled bloom and still same versions and same issues. 

I’m just running bloom-release with new and existing packages. Nothing special.

**Comment by wjwwood** [comment]
Can one of you (@SteveMacenski or @JWhitleyAStuff) provide the exact case, exact arguments, so that we can eliminate some other issue?

The only advice I can give you is to make sure you don't have these libraries installed from both apt and pip, as there are know issues where pip will override apt, so even if you update from apt it can be using an older version from pip. So maybe make sure that you look in both `/usr` (where apt installs things) and `/usr/local` (where pip installs things).

**Comment by wjwwood** [comment]
You can also try a virtual env, where you install bloom and use it there maybe even with the `--no-site-packages` (apparently this is the default behavior now anyways).

**Comment by dirk-thomas** [comment]
> So maybe make sure that you look in both /usr (where apt installs things) and /usr/local (where pip installs things).

You might want to also check `~/.local`.

**Comment by SteveMacenski** [comment]
`bloom-release --rosdistro dashing --track dashing ros2_ouster_driver` is an exact example. But I've seen this in every bloom release since Josh opened the ticket. 

I didn't update or change anything until this became a problem - so I'm pretty sure its not a pip issue on my end (though I may have now introduced one while debugging). I'm not generally a python developer so I touch pip maybe once a month. Overall, this isn't a huge deal to me. But I did just upgrade my old 16.04 machine to 18.04 last week with a clean eloquent / melodic install, no modifications, and it still has this.

**Comment by JWhitleyAStuff** [comment]
I've confirmed that this is independent of Python version (at least between 2 and 3). Happens on both.

**Comment by wjwwood** [comment]
I just did a bloom release from a fresh virtual env, installing bloom just now, and it went without a hitch:

https://github.com/ros/rosdistro/pull/23587

Unfortunately, without some new information or the ability to reproduce it, I don't think we can help further.

**Comment by JWhitleyAStuff** [comment]
Hey, @SteveMacenski - Question: What do you and I have in common in our GitHub accounts that the others who have tried this with success don't? I'll give you a hint: This is a problem on Linux but it wouldn't be on Windows.

**Comment by SteveMacenski** [comment]
No idea -- I'm extremely unfamiliar with software development on Windows to compare against.

**Comment by JWhitleyAStuff** [comment]
Capital letters. Check your `.config/bloom` file and see if the "github_user" field is "stevemacenski" or "SteveMacenski". I changed mine and it works now.

**Comment by JWhitleyAStuff** [comment]
(after a ton of work involving `mitmproxy`)

**Comment by wjwwood** [comment]
Woah, that's crazy, I still don't have an idea why though, is it how we call GitHub's web API or something wrong with a python library we're using?

**Comment by JWhitleyAStuff** [comment]
@wjwwood They must have changed the API's case-sensitivity and @SteveMacenski and I were the only ones who noticed that use `bloom` since we're some of the few that have capital letters in our usernames. I'm looking for their release notes now to see if I can find a related change.

**Comment by SteveMacenski** [comment]
`{"github_user": "stevemacenski", "oauth_token": "[token]"}`, should it be caps?

That's so ****ing stupid. Thank you for debugging. After trying it on 3 machines, I just gave up and accepted this as the new state of my reality

**Comment by JWhitleyAStuff** [comment]
@wjwwood / @SteveMacenski - According to https://happygitwithr.com/github-acct.html, Github should treat them as case-insensitive. It must be a bug in the API. I'll register a bug and see what they say. Thanks to both of you and @dirk-thomas and @tfoote for looking into this.

**Comment by JWhitleyAStuff** [comment]
Ref to request: https://github.community/t5/GitHub-API-Development-and/Endpoint-for-Creating-Pull-Requests-is-Username-case-sensitive/m-p/44181

**Comment by wjwwood** [comment]
Thanks for tracking it down and opening the support issue.

**Comment by nuclearsandwich** [comment]
What do people think of updating the issue title here to something like

> GitHub API uses case sensitive usernames. GitHubException - Failed to create pull request: 422 Unprocessable Entity

If GitHub comes back and says that case sensitive usernames is The New Way we can also catch this specifically in Bloom and suggest checking the casing.
