### ISSUE TITLE
Release for noetic fails with errors

### ISSUE THREAD

**Issue by cdoehn** [ros-infrastructure/bloom#635]
We get an error when trying to release a new version of our package.

<pre><font color="#4E9A06"><b>user</b></font>:<font color="#3465A4"><b>~/catkin_ws/src/psen_scan_v2</b></font>$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
<font color="#4E9A06"><b>user</b></font>:<font color="#3465A4"><b>~/catkin_ws/src/psen_scan_v2</b></font>$ bloom-release --version
0.10.7
<font color="#4E9A06"><b>user</b></font>:<font color="#3465A4"><b>~/catkin_ws/src/psen_scan_v2</b></font>$ bloom-release psen_scan_v2 --rosdistro noetic
ROS Distro index file associate with commit &apos;7695275196ce2621a2f4719c4a24ff895c026993&apos;
New ROS Distro index url: &apos;https://raw.githubusercontent.com/ros/rosdistro/7695275196ce2621a2f4719c4a24ff895c026993/index-v4.yaml&apos;
<font color="#4E9A06"><b>==&gt; </b></font>Fetching &apos;psen_scan_v2&apos; repository from &apos;https://github.com/PilzDE/psen_scan_v2-release.git&apos;
Cloning into &apos;/tmp/tmp9_v3uuhy&apos;...
remote: Enumerating objects: 1682, done.
remote: Counting objects: 100% (1682/1682), done.
remote: Compressing objects: 100% (1078/1078), done.
remote: Total 1682 (delta 674), reused 1531 (delta 528), pack-reused 0
Receiving objects: 100% (1682/1682), 2.22 MiB | 26.76 MiB/s, done.
Resolving deltas: 100% (674/674), done.
<font color="#4E9A06"><b>==&gt; </b></font>Testing for push permission on release repository
<font color="#3465A4"><b>==&gt; </b></font>git remote -v
origin	https://github.com/PilzDE/psen_scan_v2-release.git (fetch)
origin	https://github.com/PilzDE/psen_scan_v2-release.git (push)
<font color="#3465A4"><b>==&gt; </b></font>git push --dry-run
Username for &apos;https://github.com&apos;: cdoehn
Password for &apos;https://cdoehn@github.com&apos;: 
Everything up-to-date
<font color="#4E9A06"><b>==&gt; </b></font>Releasing &apos;psen_scan_v2&apos; using release track &apos;noetic&apos;
<font color="#3465A4"><b>==&gt; </b></font><b>git-bloom-release noetic</b>
Processing release track settings for &apos;noetic&apos;
Checking upstream devel branch &apos;main&apos; for package.xml(s)
Cloning into &apos;/tmp/tmpija88sft/upstream&apos;...
remote: Enumerating objects: 2013, done.
remote: Counting objects: 100% (214/214), done.
remote: Compressing objects: 100% (126/126), done.
remote: Total 2013 (delta 100), reused 174 (delta 82), pack-reused 1799
Receiving objects: 100% (2013/2013), 4.37 MiB | 31.73 MiB/s, done.
Resolving deltas: 100% (1344/1344), done.
Looking for packages in &apos;main&apos; branch... found &apos;psen_scan_v2&apos;.
Detected version &apos;0.2.1&apos; from package(s): [&apos;psen_scan_v2&apos;]

Executing release track &apos;noetic&apos;
<font color="#3465A4"><b>==&gt; </b></font><b>bloom-export-upstream /tmp/tmpija88sft/upstream git --tag 0.2.1 --display-uri https://github.com/PilzDE/psen_scan_v2.git --name upstream --output-dir /tmp/tmptrcbbv5q</b>
Checking out repository at &apos;https://github.com/PilzDE/psen_scan_v2.git&apos; to reference &apos;0.2.1&apos;.
Exporting to archive: &apos;/tmp/tmptrcbbv5q/upstream-0.2.1.tar.gz&apos;
md5: ef5f347dee09ee991241ffa1299a5646

<font color="#3465A4"><b>==&gt; </b></font><b>git-bloom-import-upstream /tmp/tmptrcbbv5q/upstream-0.2.1.tar.gz  --release-version 0.2.1 --replace</b>
The latest upstream tag in the release repository is &apos;<b>upstream/0.2.0</b>&apos;.
Importing archive into upstream branch...
Creating tag: &apos;upstream/0.2.1&apos;
I&apos;m happy.  You should be too.

<font color="#3465A4"><b>==&gt; </b></font><b>git-bloom-generate -y rosrelease noetic --source upstream -i 1</b>
Releasing package: [&apos;psen_scan_v2&apos;]
Releasing package &apos;psen_scan_v2&apos; for &apos;noetic&apos; to: &apos;release/noetic/psen_scan_v2&apos;

<font color="#3465A4"><b>==&gt; </b></font><b>git-bloom-generate -y rosdebian --prefix release/noetic noetic -i 1 --os-name ubuntu</b>
Generating source debs for the packages: [&apos;psen_scan_v2&apos;]
Debian Incremental Version: 1
Debian Distributions: [&apos;focal&apos;]
Releasing for rosdistro: noetic

Pre-verifying Debian dependency keys...
Running &apos;rosdep update&apos;...
All keys are <font color="#4E9A06">OK</font>

Placing debian template files into &apos;debian/noetic/psen_scan_v2&apos; branch.
<font color="#3465A4"><b>==&gt;</b></font> Placing templates files in the &apos;debian&apos; folder.

<font color="#3465A4">####</font>
<font color="#3465A4">#### Generating &apos;</font><font color="#3465A4"><b>focal</b></font><font color="#3465A4">&apos; debian for package &apos;</font><font color="#3465A4"><b>psen_scan_v2</b></font><font color="#3465A4">&apos; at version &apos;</font><font color="#3465A4"><b>0.2.1-1</b></font><font color="#3465A4">&apos;</font>
<font color="#3465A4">####</font>
Generating debian for focal...
<font color="#C4A000">No homepage set, defaulting to &apos;&apos;</font>
Package &apos;psen-scan-v2&apos; has dependencies:
<font color="#75507B">Run Dependencies:</font>
  <u style="text-decoration-style:single">rosdep key           =&gt; focal key</u>
  <font color="#06989A">robot_state_publisher </font><font color="#75507B">=&gt; </font><font color="#06989A">[&apos;ros-noetic-robot-state-publisher&apos;]</font>
  <font color="#06989A">roslaunch            </font><font color="#75507B">=&gt; </font><font color="#06989A">[&apos;ros-noetic-roslaunch&apos;]</font>
  <font color="#06989A">rviz                 </font><font color="#75507B">=&gt; </font><font color="#06989A">[&apos;ros-noetic-rviz&apos;]</font>
  <font color="#06989A">xacro                </font><font color="#75507B">=&gt; </font><font color="#06989A">[&apos;ros-noetic-xacro&apos;]</font>
  <font color="#06989A">fmt                  </font><font color="#75507B">=&gt; </font><font color="#06989A">[&apos;libfmt-dev&apos;]</font>
  <font color="#06989A">roscpp               </font><font color="#75507B">=&gt; </font><font color="#06989A">[&apos;ros-noetic-roscpp&apos;]</font>
  <font color="#06989A">sensor_msgs          </font><font color="#75507B">=&gt; </font><font color="#06989A">[&apos;ros-noetic-sensor-msgs&apos;]</font>
  <font color="#06989A">rosconsole_bridge    </font><font color="#75507B">=&gt; </font><font color="#06989A">[&apos;ros-noetic-rosconsole-bridge&apos;]</font>
<font color="#75507B">Build and Build Tool Dependencies:</font>
  <u style="text-decoration-style:single">rosdep key           =&gt; focal key</u>
  <font color="#06989A">fmt                  </font><font color="#75507B">=&gt; </font><font color="#06989A">[&apos;libfmt-dev&apos;]</font>
  <font color="#06989A">roscpp               </font><font color="#75507B">=&gt; </font><font color="#06989A">[&apos;ros-noetic-roscpp&apos;]</font>
  <font color="#06989A">sensor_msgs          </font><font color="#75507B">=&gt; </font><font color="#06989A">[&apos;ros-noetic-sensor-msgs&apos;]</font>
  <font color="#06989A">rosconsole_bridge    </font><font color="#75507B">=&gt; </font><font color="#06989A">[&apos;ros-noetic-rosconsole-bridge&apos;]</font>
  <font color="#06989A">catkin               </font><font color="#75507B">=&gt; </font><font color="#06989A">[&apos;ros-noetic-catkin&apos;]</font>
  <font color="#06989A">code_coverage        </font><font color="#75507B">=&gt; </font><font color="#06989A">[&apos;ros-noetic-code-coverage&apos;]</font>
  <font color="#06989A">rostest              </font><font color="#75507B">=&gt; </font><font color="#06989A">[&apos;ros-noetic-rostest&apos;]</font>
  <font color="#06989A">rosunit              </font><font color="#75507B">=&gt; </font><font color="#06989A">[&apos;ros-noetic-rosunit&apos;]</font>
  <font color="#06989A">roslaunch            </font><font color="#75507B">=&gt; </font><font color="#06989A">[&apos;ros-noetic-roslaunch&apos;]</font>
  <font color="#06989A">pilz_testutils       </font><font color="#75507B">=&gt; </font><font color="#06989A">[&apos;ros-noetic-pilz-testutils&apos;]</font>
  <font color="#06989A">rosbag               </font><font color="#75507B">=&gt; </font><font color="#06989A">[&apos;ros-noetic-rosbag&apos;]</font>
ROS Distro index file associate with commit &apos;7695275196ce2621a2f4719c4a24ff895c026993&apos;
New ROS Distro index url: &apos;https://raw.githubusercontent.com/ros/rosdistro/7695275196ce2621a2f4719c4a24ff895c026993/index-v4.yaml&apos;
<font color="#3465A4"><b>==&gt;</b></font> In place processing templates in &apos;debian&apos; folder.
Expanding &apos;debian/copyright.em&apos; -&gt; &apos;debian/copyright&apos;
Expanding &apos;debian/changelog.em&apos; -&gt; &apos;debian/changelog&apos;
Expanding &apos;debian/control.em&apos; -&gt; &apos;debian/control&apos;
Expanding &apos;debian/source/format.em&apos; -&gt; &apos;debian/source/format&apos;
Expanding &apos;debian/source/options.em&apos; -&gt; &apos;debian/source/options&apos;
Expanding &apos;debian/rules.em&apos; -&gt; &apos;debian/rules&apos;
Expanding &apos;debian/gbp.conf.em&apos; -&gt; &apos;debian/gbp.conf&apos;
Expanding &apos;debian/compat.em&apos; -&gt; &apos;debian/compat&apos;
Creating tag: debian/ros-noetic-psen-scan-v2_0.2.1-1_focal
<font color="#3465A4">####</font>
<font color="#3465A4">#### </font><font color="#4E9A06">Successfully</font><font color="#3465A4"> generated &apos;</font><font color="#3465A4"><b>focal</b></font><font color="#3465A4">&apos; debian for package &apos;</font><font color="#3465A4"><b>psen_scan_v2</b></font><font color="#3465A4">&apos; at version &apos;</font><font color="#3465A4"><b>0.2.1-1</b></font><font color="#3465A4">&apos;</font>
<font color="#3465A4">####</font>

<font color="#3465A4"><b>==&gt; </b></font><b>git-bloom-generate -y rosdebian --prefix release/noetic noetic -i 1 --os-name debian --os-not-required</b>
Generating source debs for the packages: [&apos;psen_scan_v2&apos;]
Debian Incremental Version: 1
Debian Distributions: [&apos;buster&apos;]
Releasing for rosdistro: noetic

Pre-verifying Debian dependency keys...
Running &apos;rosdep update&apos;...
All keys are <font color="#4E9A06">OK</font>

Placing debian template files into &apos;debian/noetic/psen_scan_v2&apos; branch.
<font color="#3465A4"><b>==&gt;</b></font> Placing templates files in the &apos;debian&apos; folder.

<font color="#3465A4">####</font>
<font color="#3465A4">#### Generating &apos;</font><font color="#3465A4"><b>buster</b></font><font color="#3465A4">&apos; debian for package &apos;</font><font color="#3465A4"><b>psen_scan_v2</b></font><font color="#3465A4">&apos; at version &apos;</font><font color="#3465A4"><b>0.2.1-1</b></font><font color="#3465A4">&apos;</font>
<font color="#3465A4">####</font>
Generating debian for buster...
<font color="#C4A000">No homepage set, defaulting to &apos;&apos;</font>
Package &apos;psen-scan-v2&apos; has dependencies:
<font color="#75507B">Run Dependencies:</font>
  <u style="text-decoration-style:single">rosdep key           =&gt; buster key</u>
  <font color="#06989A">robot_state_publisher </font><font color="#75507B">=&gt; </font><font color="#06989A">[&apos;ros-noetic-robot-state-publisher&apos;]</font>
  <font color="#06989A">roslaunch            </font><font color="#75507B">=&gt; </font><font color="#06989A">[&apos;ros-noetic-roslaunch&apos;]</font>
  <font color="#06989A">rviz                 </font><font color="#75507B">=&gt; </font><font color="#06989A">[&apos;ros-noetic-rviz&apos;]</font>
  <font color="#06989A">xacro                </font><font color="#75507B">=&gt; </font><font color="#06989A">[&apos;ros-noetic-xacro&apos;]</font>
  <font color="#06989A">fmt                  </font><font color="#75507B">=&gt; </font><font color="#06989A">[&apos;libfmt-dev&apos;]</font>
  <font color="#06989A">roscpp               </font><font color="#75507B">=&gt; </font><font color="#06989A">[&apos;ros-noetic-roscpp&apos;]</font>
  <font color="#06989A">sensor_msgs          </font><font color="#75507B">=&gt; </font><font color="#06989A">[&apos;ros-noetic-sensor-msgs&apos;]</font>
  <font color="#06989A">rosconsole_bridge    </font><font color="#75507B">=&gt; </font><font color="#06989A">[&apos;ros-noetic-rosconsole-bridge&apos;]</font>
<font color="#75507B">Build and Build Tool Dependencies:</font>
  <u style="text-decoration-style:single">rosdep key           =&gt; buster key</u>
  <font color="#06989A">fmt                  </font><font color="#75507B">=&gt; </font><font color="#06989A">[&apos;libfmt-dev&apos;]</font>
  <font color="#06989A">roscpp               </font><font color="#75507B">=&gt; </font><font color="#06989A">[&apos;ros-noetic-roscpp&apos;]</font>
  <font color="#06989A">sensor_msgs          </font><font color="#75507B">=&gt; </font><font color="#06989A">[&apos;ros-noetic-sensor-msgs&apos;]</font>
  <font color="#06989A">rosconsole_bridge    </font><font color="#75507B">=&gt; </font><font color="#06989A">[&apos;ros-noetic-rosconsole-bridge&apos;]</font>
  <font color="#06989A">catkin               </font><font color="#75507B">=&gt; </font><font color="#06989A">[&apos;ros-noetic-catkin&apos;]</font>
  <font color="#06989A">code_coverage        </font><font color="#75507B">=&gt; </font><font color="#06989A">[&apos;ros-noetic-code-coverage&apos;]</font>
  <font color="#06989A">rostest              </font><font color="#75507B">=&gt; </font><font color="#06989A">[&apos;ros-noetic-rostest&apos;]</font>
  <font color="#06989A">rosunit              </font><font color="#75507B">=&gt; </font><font color="#06989A">[&apos;ros-noetic-rosunit&apos;]</font>
  <font color="#06989A">roslaunch            </font><font color="#75507B">=&gt; </font><font color="#06989A">[&apos;ros-noetic-roslaunch&apos;]</font>
  <font color="#06989A">pilz_testutils       </font><font color="#75507B">=&gt; </font><font color="#06989A">[&apos;ros-noetic-pilz-testutils&apos;]</font>
  <font color="#06989A">rosbag               </font><font color="#75507B">=&gt; </font><font color="#06989A">[&apos;ros-noetic-rosbag&apos;]</font>
ROS Distro index file associate with commit &apos;7695275196ce2621a2f4719c4a24ff895c026993&apos;
New ROS Distro index url: &apos;https://raw.githubusercontent.com/ros/rosdistro/7695275196ce2621a2f4719c4a24ff895c026993/index-v4.yaml&apos;
<font color="#3465A4"><b>==&gt;</b></font> In place processing templates in &apos;debian&apos; folder.
Expanding &apos;debian/copyright.em&apos; -&gt; &apos;debian/copyright&apos;
Expanding &apos;debian/changelog.em&apos; -&gt; &apos;debian/changelog&apos;
Expanding &apos;debian/control.em&apos; -&gt; &apos;debian/control&apos;
Expanding &apos;debian/source/format.em&apos; -&gt; &apos;debian/source/format&apos;
Expanding &apos;debian/source/options.em&apos; -&gt; &apos;debian/source/options&apos;
Expanding &apos;debian/rules.em&apos; -&gt; &apos;debian/rules&apos;
Expanding &apos;debian/gbp.conf.em&apos; -&gt; &apos;debian/gbp.conf&apos;
Expanding &apos;debian/compat.em&apos; -&gt; &apos;debian/compat&apos;
Creating tag: debian/ros-noetic-psen-scan-v2_0.2.1-1_buster
<font color="#3465A4">####</font>
<font color="#3465A4">#### </font><font color="#4E9A06">Successfully</font><font color="#3465A4"> generated &apos;</font><font color="#3465A4"><b>buster</b></font><font color="#3465A4">&apos; debian for package &apos;</font><font color="#3465A4"><b>psen_scan_v2</b></font><font color="#3465A4">&apos; at version &apos;</font><font color="#3465A4"><b>0.2.1-1</b></font><font color="#3465A4">&apos;</font>
<font color="#3465A4">####</font>

<font color="#3465A4"><b>==&gt; </b></font><b>git-bloom-generate -y rosrpm --prefix release/noetic noetic -i 1 --os-name fedora</b>
Generating source RPMs for the packages: [&apos;psen_scan_v2&apos;]
RPM Incremental Version: 1
RPM OS: fedora
RPM Distributions: [&apos;32&apos;]
Releasing for rosdistro: noetic

Pre-verifying RPM dependency keys...
Running &apos;rosdep update&apos;...
All keys are <font color="#4E9A06">OK</font>

<font color="#CC0000"><b> [git-bloom-patch export]: &apos;execute_command&apos; failed to call &apos;git format-patch -M -B 496bc3b...rpm/noetic/psen_scan_v2&apos; which had a return code (128):</b></font>
<font color="#CC0000"><b> [git-bloom-patch export]: ```</b></font>
fatal: ambiguous argument &apos;496bc3b...rpm/noetic/psen_scan_v2&apos;: unknown revision or path not in the working tree.
Use &apos;--&apos; to separate paths from revisions, like this:
&apos;git &lt;command&gt; [&lt;revision&gt;...] -- [&lt;file&gt;...]&apos;

<font color="#CC0000"><b> [git-bloom-patch export]: ```</b></font>
Traceback (most recent call last):
  File <font color="#06989A">&quot;/usr/local/lib/python3.8/dist-packages/bloom-0.10.7-py3.8.egg/bloom/commands/git/generate.py&quot;</font>, line <font color="#3465A4">101</font>, in try_execute
    retcode = func(*args, **kwargs)
  File <font color="#06989A">&quot;/usr/local/lib/python3.8/dist-packages/bloom-0.10.7-py3.8.egg/bloom/logging.py&quot;</font>, line <font color="#3465A4">211</font>, in decorated
    <font color="#3465A4">return</font> f(*args, **kwds)
  File <font color="#06989A">&quot;/usr/local/lib/python3.8/dist-packages/bloom-0.10.7-py3.8.egg/bloom/commands/git/patch/export_cmd.py&quot;</font>, line <font color="#3465A4">53</font>, in export_patches
    execute_command(cmd, cwd=directory)
  File <font color="#06989A">&quot;/usr/local/lib/python3.8/dist-packages/bloom-0.10.7-py3.8.egg/bloom/util.py&quot;</font>, line <font color="#3465A4">462</font>, in execute_command
    <font color="#3465A4">raise</font> CalledProcessError(result, cmd)
<font color="#CC0000"><b>subprocess.CalledProcessError</b></font>: Command &apos;git format-patch -M -B 496bc3b...rpm/noetic/psen_scan_v2&apos; returned non-zero exit status 128.

<font color="#CC0000"><b>Error calling git-bloom-patch export: Command &apos;git format-patch -M -B 496bc3b...rpm/noetic/psen_scan_v2&apos; returned non-zero exit status 128.</b></font>
<font color="#CC0000"><b>git-bloom-patch export returned exit code (128)</b></font>
<font color="#CC0000"><b>&lt;== </b></font>Error running command &apos;<b>[&apos;/bin/git-bloom-generate&apos;, &apos;-y&apos;, &apos;rosrpm&apos;, &apos;--prefix&apos;, &apos;release/noetic&apos;, &apos;noetic&apos;, &apos;-i&apos;, &apos;1&apos;, &apos;--os-name&apos;, &apos;fedora&apos;]&apos;</b>
<font color="#CC0000"><b>Release failed, exiting.</b></font>
<font color="#4E9A06"><b>user</b></font>:<font color="#3465A4"><b>~/catkin_ws/src/psen_scan_v2</b></font>$</pre>

**Comment by rfeistenauer** [comment]
Could it be the same as #392?

**Comment by cdoehn** [comment]
The [workarround](https://github.com/ros-infrastructure/bloom/issues/392#issuecomment-219086724) mentioned in #392 does not work. I expanded the SHA hash from 496bc3b to 496bc3bb2f8.


<pre><font color="#3465A4"><b>==&gt; </b></font><b>git-bloom-generate -y rosrpm --prefix release/noetic noetic -i 1 --os-name fedora</b>
Generating source RPMs for the packages: [&apos;psen_scan_v2&apos;]
RPM Incremental Version: 1
RPM OS: fedora
RPM Distributions: [&apos;32&apos;]
Releasing for rosdistro: noetic

Pre-verifying RPM dependency keys...
Running &apos;rosdep update&apos;...
All keys are <font color="#4E9A06">OK</font>

<font color="#CC0000"><b> [git-bloom-patch export]: &apos;execute_command&apos; failed to call &apos;git format-patch -M -B 496bc3bb2f8...rpm/noetic/psen_scan_v2&apos; which had a return code (128):</b></font>
<font color="#CC0000"><b> [git-bloom-patch export]: ```</b></font>
fatal: ambiguous argument &apos;496bc3bb2f8...rpm/noetic/psen_scan_v2&apos;: unknown revision or path not in the working tree.
Use &apos;--&apos; to separate paths from revisions, like this:
&apos;git &lt;command&gt; [&lt;revision&gt;...] -- [&lt;file&gt;...]&apos;

<font color="#CC0000"><b> [git-bloom-patch export]: ```</b></font>
Traceback (most recent call last):
  File <font color="#06989A">&quot;/usr/local/lib/python3.8/dist-packages/bloom-0.10.7-py3.8.egg/bloom/commands/git/generate.py&quot;</font>, line <font color="#3465A4">101</font>, in try_execute
    retcode = func(*args, **kwargs)
  File <font color="#06989A">&quot;/usr/local/lib/python3.8/dist-packages/bloom-0.10.7-py3.8.egg/bloom/logging.py&quot;</font>, line <font color="#3465A4">211</font>, in decorated
    <font color="#3465A4">return</font> f(*args, **kwds)
  File <font color="#06989A">&quot;/usr/local/lib/python3.8/dist-packages/bloom-0.10.7-py3.8.egg/bloom/commands/git/patch/export_cmd.py&quot;</font>, line <font color="#3465A4">53</font>, in export_patches
    execute_command(cmd, cwd=directory)
  File <font color="#06989A">&quot;/usr/local/lib/python3.8/dist-packages/bloom-0.10.7-py3.8.egg/bloom/util.py&quot;</font>, line <font color="#3465A4">462</font>, in execute_command
    <font color="#3465A4">raise</font> CalledProcessError(result, cmd)
<font color="#CC0000"><b>subprocess.CalledProcessError</b></font>: Command &apos;git format-patch -M -B 496bc3bb2f8...rpm/noetic/psen_scan_v2&apos; returned non-zero exit status 128.

<font color="#CC0000"><b>Error calling git-bloom-patch export: Command &apos;git format-patch -M -B 496bc3bb2f8...rpm/noetic/psen_scan_v2&apos; returned non-zero exit status 128.</b></font>
<font color="#CC0000"><b>git-bloom-patch export returned exit code (128)</b></font>
<font color="#CC0000"><b>&lt;== </b></font>Error running command &apos;<b>[&apos;/bin/git-bloom-generate&apos;, &apos;-y&apos;, &apos;rosrpm&apos;, &apos;--prefix&apos;, &apos;release/noetic&apos;, &apos;noetic&apos;, &apos;-i&apos;, &apos;1&apos;, &apos;--os-name&apos;, &apos;fedora&apos;]&apos;</b>
<font color="#CC0000"><b>Release failed, exiting.</b></font>
</pre>

**Comment by cdoehn** [comment]
Deleting the release repo und creating it again solved the issue.
