### ISSUE TITLE
All docs links 404?

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-infrastructure/bloom#640]
Both http://ros-infrastructure.github.com/bloom/doc and http://ros-infrastructure.github.com/bloom end in `404` for me at the moment.

Has something stopped working?

**Comment by gavanderhoorn** [comment]
I suddenly remembered https://bloom.readthedocs.io which does work.

Should all those other references be updated to point to RTD instead?

**Comment by nuclearsandwich** [comment]
> Should all those other references be updated to point to RTD instead?

Yes please!

**Comment by gavanderhoorn** [comment]
See #644.

**Comment by gavanderhoorn** [comment]
I've checked the ROS wiki and it already points to the RTD.

**Comment by gavanderhoorn** [comment]
Some of it does still work though, not sure what's going on: http://ros-infrastructure.github.io/bloom/doc/0.2.1/index.html

**Comment by nuclearsandwich** [comment]
The gh-pages branch hasn't been updated since 2014 so but RTD is also still pointing to an older version of bloom. Giving bloom docs a full overhaul is actually on the ROS infrastructure roadmap for coming months so getting these updated should follow soon.
