### ISSUE TITLE
'execute_command' failed to call 'git mv rpm/template.spec rpm/ros-rolling-<package>.spec' which had a return code (128):

### ISSUE THREAD

**Issue by ijnek** [ros-infrastructure/bloom#680]
Releasing a package fails on RHEL8.

I'm trying to release an update to a package. When I run the command below:

```
bloom-release --rosdistro rolling rcss3d_agent
```

I get the following error and the release fails:

```sh
####
#### Generating 'rhel 8' RPM for package 'rcss3d_agent_msgs' at version '0.4.0-1'
####
Generating RPM for rhel 8...
No homepage set
Package 'rcss3d-agent-msgs' has dependencies:
Run Dependencies:
  rosdep key           => rhel 8 key
  builtin_interfaces   => ['ros-rolling-builtin-interfaces']
  rosidl_default_runtime => ['ros-rolling-rosidl-default-runtime']
Build and Build Tool Dependencies:
  rosdep key           => rhel 8 key
  builtin_interfaces   => ['ros-rolling-builtin-interfaces']
  rosidl_default_generators => ['ros-rolling-rosidl-default-generators']
  ament_cmake          => ['ros-rolling-ament-cmake']
==> In place processing templates in 'rpm' folder.
Expanding 'rpm/template.spec.em' -> 'rpm/template.spec'
'execute_command' failed to call 'git mv rpm/template.spec rpm/ros-rolling-rcss3d-agent-msgs.spec' which had a return code (128):
'''
fatal: not under version control, source=rpm/template.spec, destination=rpm/ros-rolling-rcss3d-agent-msgs.spec

'''
Traceback (most recent call last):
  File "/home/ijnek/.local/lib/python3.10/site-packages/bloom/commands/git/generate.py", line 101, in try_execute
    retcode = func(*args, **kwargs)
  File "/home/ijnek/.local/lib/python3.10/site-packages/bloom/generators/rpm/generator.py", line 672, in post_rebase
    data = self.generate_rpm(package, distro)
  File "/home/ijnek/.local/lib/python3.10/site-packages/bloom/generators/rpm/generator.py", line 809, in generate_rpm
    execute_command('git mv ' + rpm_dir + '/template.spec ' + rpm_dir + '/' + subs['Package'] + '.spec')
  File "/home/ijnek/.local/lib/python3.10/site-packages/bloom/util.py", line 451, in execute_command
    raise CalledProcessError(result, cmd)
subprocess.CalledProcessError: Command 'git mv rpm/template.spec rpm/ros-rolling-rcss3d-agent-msgs.spec' returned non-zero exit status 128.

Error calling generator post_rebase: Command 'git mv rpm/template.spec rpm/ros-rolling-rcss3d-agent-msgs.spec' returned non-zero exit status 128.
generator post_rebase returned exit code (128)
<== Error running command '['/home/ijnek/.local/bin/git-bloom-generate', '-y', 'rosrpm', '--prefix', 'release/rolling', 'rolling', '-i', '1', '--os-name', 'rhel']'
Release failed, exiting.
```

* OS: Ubuntu22.04
* Distro: Rolling
* Bloom version:  0.11.1 (newest version according to apt)

I'll look into this, but I want to see if others are also having this issue or not.

**Comment by cottsay** [comment]
I'm not able to reproduce this on 22.04 or Fedora. Both using Bloom 0.11.1, both run the command you gave successfully (until I aborted the final push to the release repository, of course).

**Comment by ijnek** [comment]
Thanks @cottsay, I'll see if I can preproduce it in a fresh Ubuntu22.04 container.

**Comment by ijnek** [comment]
Update - I don't see the error show up in a fresh ubuntu22.04 container. I will close this issue off once I figure out why it's failing locally.

**Comment by ijnek** [comment]
The issue was due to *.spec files beign ignored by git.

I recently set up a global gitignore file based off [github/gitignore](https://github.com/github/gitignore), where Python.gitignore contains [a line](https://github.com/github/gitignore/blob/e5323759e387ba347a9d50f8b0ddd16502eb71d4/Python.gitignore#L33) that ignores *.spec files. This meant that the .spec files weren't detected by git to perform this line:

[``execute_command('git mv ' + rpm_dir + '/template.spec ' + rpm_dir + '/' + subs['Package'] + '.spec')``](https://github.com/ros-infrastructure/bloom/blob/813180c5f4d99af2c9d36330e5738a25d18f5ebf/bloom/generators/rpm/generator.py#L808)
