### ISSUE TITLE
bloom-release does not open PR on rosdistro

### ISSUE THREAD

**Issue by berndpfrommer** [ros-infrastructure/bloom#706]
Following instructions [here](https://docs.ros.org/en/humble/How-To-Guides/Releasing/First-Time-Release.html) I hit a snag when running bloom-release. It won't open a PR on rosdistro.

Running on Ubuntu 22.04 with ROS2 humble. Bloom release is 0.11.2

Here is the error message I get:

```
bloom-release --new-track --rosdistro humble --track humble event_array_msgs -d
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning:  is an invalid version and will not be supported in a future release
  warnings.warn(
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning:  is an invalid version and will not be supported in a future release
  warnings.warn(
ROS Distro index file associate with commit 'a8f655c921835a521417b8dd4318da74eb067ab7'
New ROS Distro index url: 'https://raw.githubusercontent.com/ros/rosdistro/a8f655c921835a521417b8dd4318da74eb067ab7/index-v4.yaml'
Specified repository 'event_array_msgs' is not in the distribution file located at 'https://raw.githubusercontent.com/ros/rosdistro/a8f655c921835a521417b8dd4318da74eb067ab7/humble/distribution.yaml'
Did you mean one of these: 'clearpath_msgs'?
Could not determine release repository url for repository 'event_array_msgs' of distro 'humble'
You can continue the release process by manually specifying the location of the RELEASE repository.
To be clear this is the url of the RELEASE repository not the upstream repository.
For release repositories on GitHub, you should provide the `https://` url which should end in `.git`.
Here is the url for a typical release repository on GitHub: https://github.com/ros-gbp/rviz-release.git
==> Looking for a release of this repository in a different distribution...
No reasonable default release repository url could be determined from previous releases.
Release repository url [press enter to abort]: ^C
User exited at prompt.

```

**Comment by ijnek** [comment]
Hi @berndpfrommer, I have a suspicion that you just followed just the instructions under the "Bloom Release" heading from that guide. The guide is intended to be a step-by-step guide, so you must complete all of the steps prior to that step and have a release repository set up before proceeding to the "Bloom Release" step.

**Comment by berndpfrommer** [comment]
@ijnek thanks for your quick response!
The instructions say that before setting up a release repository I am supposed to create a release team via a New Release Team Issue. But the template for the New Release Team Issue says I must first create a release repository, which in turn requires a PR against rosdistro for naming review.
But the PR template there says I should use bloom for generating the PR, see below. So am I now supposed to file the PR manually, or is bloom supposed to do that automatically? I'm confused.
```
 <!-- Thank you for contributing a change to the rosdistro. There are two primary types of submissions.
Please select the appropriate template from below: ROSDEP_RULE_TEMPLATE or DOC_INDEX_TEMPLATE

If you're making a new release with bloom please use bloom to create the pull request automatically.
If you've already run the release bloom has a `--pull-request-only` option you can use.-->

<!-- ROSDEP_RULE_TEMPLATE: Submitter Please review the contributing guidelines: https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md -->

```

**Comment by clalancette** [comment]
> But the PR template there says I should use bloom for generating the PR, see below. So am I now supposed to file the PR manually, or is bloom supposed to do that automatically? I'm confused.

For a naming request, you should open one manually, just for the sources.  That is, you should add an entry like [the one here](https://github.com/ros/rosdistro/blob/75d49c0677946cb069c478dd8f352dc9e1d27813/rolling/distribution.yaml#L4245-L4254).  `bloom` can only be used once you have a release repository setup.

If you'd like to submit a change to https://github.com/ros/rosdistro/blob/master/.github/pull_request_template.md?plain=1 to improve the wording there, it would be much appreciated.
